### ISSUE TITLE
CakePdf in CakePHP 3

### ISSUE THREAD

**Issue by matrich** [FriendsOfCake/CakePdf#102]
Does CakePdf work in CakePHP 3 as I have tried the composer installation and it is not working? 

I have then put the plugin in plugins direction and run the composer dumpautoload command but the plugin is giving errors of Class 'App' not found in plugins\CakePdf\Config\bootstrap.php on line 2 etc. 

Please help.

**Comment by dakota** [comment]
It does, but you need to use the [3.0 branch](https://github.com/FriendsOfCake/CakePdf/tree/3.0)

**Comment by matrich** [comment]
Thanks for the quick response. I was able to get 3.0 branch but after the setup, I still the following error

Fatal error: [Cake\View\Exception\MissingTemplateException] Template file "Error\pdf\error500.ctp" is missing. #0 C:\wamp\www\cakephp3\vendor\cakephp\cakephp\src\View\View.php(460): Cake\View\View->_getViewFileName('error500') #1 C:\wamp\www\cakephp3\vendor\friendsofcake\cakepdf\src\View\PdfView.php(117): Cake\View\View->render('error500', 'error') #2 C:\wamp\www\cakephp3\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(331): CakePdf\View\PdfView->render('error500', 'error') #3 C:\wamp\www\cakephp3\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(301): Cake\Error\ExceptionRenderer->_outputMessageSafe('error500') #4 C:\wamp\www\cakephp3\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(303): Cake\Error\ExceptionRenderer->_outputMessage('error500') #5 C:\wamp\www\cakephp3\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(172): Cake\Error\ExceptionRenderer->_outputMessage('fatalError') #6 C:\wamp\www\cakephp3\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(145): Cake\Error\ExceptionRenderer->render() in C:\wamp\www\cakephp3\vendor\cakephp\cakephp\src\Error\ErrorHandler.php on line 157

**Comment by egalles79** [comment]
same for me...trying during a little time and same result.

**Comment by sergiomeza** [comment]
same error of @matrich

**Comment by ucasano** [comment]
same error
