### ISSUE TITLE
Workaround: WkHtmlToPdf not working on OS X

### ISSUE THREAD

**Issue by leemcd56** [FriendsOfCake/CakePdf#103]
In order to get wkhtmltopdf to work properly on OS X systems, you have to specify the location of the binary and the current working directory that's calling the binary in proc_open(). This simple workaround helped me and my other coworkers using Macs.

In /src/Pdf/Engine/WkHtmlToPdfEngine.php, _exec() function:

```
// Work-around for Mac OS X
if (php_uname('s') === "Darwin") {
    $env = array(
        'PATH' => '/usr/local/bin'
    );
    $proc = proc_open($cmd, [0 => ['pipe', 'r'], 1 => ['pipe', 'w'], 2 => ['pipe', 'a']], $pipes, __DIR__, $env);
} else {
    $proc = proc_open($cmd, [0 => ['pipe', 'r'], 1 => ['pipe', 'w'], 2 => ['pipe', 'a']], $pipes);
}
```

**Comment by Spriz** [comment]
Couldn't this just happen where you setup the CakePdf settings?

`Configure::write('CakePdf', [
    'engine' => [
        'className' => 'CakePdf.WkHtmlToPdf',
        'binary' => '/usr/local/bin/wkhtmltopdf',
    ],
    'pageSize' => 'A4',
    'encoding' => 'utf8',
    'orientation' => 'portrait'
]);`

**Comment by leemcd56** [comment]
I thought I had replied to this sooner. We had tried that and it did not work. When I passed in `__dir__` and `$env` to `proc_open` it worked perfectly and has since.

**Comment by steffex** [comment]
@leemcd56 the only thing I need to do to get it working is add the code below to my config:

```php
'CakePdf' => [
        'engine' => [
            'binary' => '/usr/local/bin/wkhtmltopdf',
        ]
    ],
```
