### ISSUE TITLE
DomPdf not working

### ISSUE THREAD

**Issue by matrich** [FriendsOfCake/CakePdf#104]
I successfully installed cakepdf and DomPdf and set all the configurations. 

When I actually view the pdf version, I get many warnings like 
Notice (8): Use of undefined constant DOMPDF_FONT_DIR - assumed 'DOMPDF_FONT_DIR' [ROOT\vendor\friendsofcake\cakepdf\src\Pdf\Engine\DomPdfEngine.php, line 32]
Notice (8): Use of undefined constant DOMPDF_CHROOT - assumed 'DOMPDF_CHROOT' [ROOT\vendor\friendsofcake\cakepdf\src\Pdf\Engine\DomPdfEngine.php, line 32]

and then two errors i.e.
Fatal error: Call to undefined function explode_url() in C:\wamp\www\cakephp3\vendor\dompdf\dompdf\include\stylesheet.cls.php on line 147
and
Fatal error: [Cake\View\Exception\MissingTemplateException] Template file "Error\pdf\error500.ctp" is missing. #0 C:\wamp\www\cakephp3\vendor\cakephp\cakephp\src\View\View.php(460): Cake\View\View->_getViewFileName('error500') #1 C:\wamp\www\cakephp3\vendor\friendsofcake\cakepdf\src\View\PdfView.php(119): Cake\View\View->render('error500', 'error') #2 C:\wamp\www\cakephp3\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(331): CakePdf\View\PdfView->render('error500', 'error') #3 C:\wamp\www\cakephp3\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(301): Cake\Error\ExceptionRenderer->_outputMessageSafe('error500') #4 C:\wamp\www\cakephp3\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(303): Cake\Error\ExceptionRenderer->_outputMessage('error500') #5 C:\wamp\www\cakephp3\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(172): Cake\Error\ExceptionRenderer->_outputMessage('fatalError') #6 C:\wamp\www\cakephp3\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(145): Cake\Error\ExceptionRenderer->render() in C:\wamp\www\cakephp3\vendor\cakephp\cakephp\src\Error\ErrorHandler.php on line 157

**Comment by dakota** [comment]
Sounds like CakePdf isn't supporting the latest dompdf. Will need to check
up on that. What version of dompdf do you have installed?

**Comment by matrich** [comment]
I installed via composer as in the documentation. I am not sure which version was downloaded but was indicating the read.md 0.6.*

I have checked in the dompdf and I have specified version 0.6.1 and it is working fine. Thanks a bunch

**Comment by matrich** [comment]
I am suspecting it could have been the v0.7.0-beta

**Comment by dakota** [comment]
Closing the issue then. Will revisit when dompdf 0.7 is stable.

**Comment by matrich** [comment]
Dear @dahota, 
I am sorry but it isn't compatible with even 0.6.1. I had changed the engine to TcPdf and I hadn't changed it back to DomPdf when I said that it works

**Comment by matrich** [comment]
DomPdf requires the default configuration file dompdf_config.inc.php while constructing the \DOMPDF() class.

Therefore add these lines to the composer autoload file before the return statement

// disable DOMPDF's internal autoloader if you are using Composer
define('DOMPDF_ENABLE_AUTOLOAD', false);
// include DOMPDF's default configuration
require_once __DIR__ . '/dompdf/dompdf/dompdf_config.inc.php';

**Comment by Redcomet120** [comment]
I'm having this same issue in CakePHP 3.x and I'm having trouble finding where to add the lines matrich mentioned above

**Comment by hstorm** [comment]
Many thanks matrich that solved the problem for me, perfect! This needs to be added to vendor/autoload.php. Additionally I had to remove

**Comment by rachid804** [comment]
Thanks @matrich works for me

**Comment by maiskovich** [comment]
Thanks @matrich

**Comment by birdy247** [comment]
FYI,

I have another solution which makes this work and means you dont have to touch the autoload file.

Add this to your app bootstrap

//DomPDF settings
define('DOMPDF_ENABLE_AUTOLOAD', false);
define('DOMPDF_ENABLE_HTML5PARSER', true);
define('DOMPDF_ENABLE_REMOTE', true);

require ROOT . DS . 'vendor' . DS . 'dompdf' . DS . 'dompdf' . DS . 'dompdf_config.inc.php';

**Comment by paanblogger** [comment]
Thanks @birdy247 . Its work.

**Comment by garimas2507** [comment]
my code is :+1: 
  public function htmltopdf($ids = NULL) {
        //  App::import('Vendor', 'dompdf', array('file' => 'dompdf' . DS . 'dompdf_config.inc.php'));
        $this->layout = false;
        def("DOMPDF_ENABLE_REMOTE", false);
        $srd = $this->FacultyRecruitmentMaster->find('first', array('conditions' => array('FacultyRecruitmentMaster.id' => $ids)));
        $this->set('STAFF', $srd);     
        $html = $this->render('faciewdetails');
        $dompdf = new DOMPDF();
        $papersize = 'legal';
        $orientation = 'portrait';
        $dompdf->load_html($html);
        $dompdf->set_paper($papersize, $orientation);
        $dompdf->render();
        // $output = $dompdf->output();
         $canvas = $dompdf->get_canvas();
              
             $canvas->page_text(540, 960, "Page {PAGE_NUM} of {PAGE_COUNT}", null, 10, array(0, 0, 0));
        $dompdf->stream($srd['StaffRecruitmentMaster']['id'] . "_completeform.pdf");
        echo $dompdf->output();
        exit;       
    } 

after clicking on download button i have found fatal error i.e.
Fatal Error

Error: Call to undefined function def()
File: /var/www/html/jammu_admin/app/Controller/FacultyController.php
Line: 266

Notice: If you want to customize this error message, create app/View/Errors/fatal_error.ctp

i think for this line def("DOMPDF_ENABLE_REMOTE", false);
what should i do please help
