### ISSUE TITLE
Template file "Pdf\newsletter.ctp" is missing."

### ISSUE THREAD

**Issue by isaacaskew** [FriendsOfCake/CakePdf#107]
I'm trying to set up my CakePdf plugin to write a file to a directory so that I can have it saved to download at a later time. I've follow the instructions in the documentation:

"The view file path would look like app/View/Pdf/newsletter.ctp. Layout file path would be like app/View/Layouts/pdf/default.ctp"

Example:

    <?php
        $CakePdf = new CakePdf();
        $CakePdf->template('newsletter', 'default');
        //get the pdf string returned
        $pdf = $CakePdf->output();
        //or write it to file directly
        $pdf = $CakePdf->write(APP . 'files' . DS . 'newsletter.pdf');
I've set up my file and called it 'newsletter.ctp' in the view file path (app/View/Pdf/newsletter.ctp) just to make sure I was doing everything exactly, because I keep getting this error:

    "Template file "Pdf\newsletter.ctp" is missing."

I've follow the directions exactly, so I'm not sure what else is the issue, although I am using the newest version of CakePHP 3. Is there any way I can manually specify an exact path instead, or does anybody know what the issue might be?

**Comment by ceeram** [comment]
docs for cake 3.0 seem to be outdated, the correct paths for 3.0 would be:

app/Template/Pdf/newsletter.ctp

and

app/Template/Layouts/pdf/default.ctp

according to the tests

Would you be able to try these paths and possibly update the readme
accordingly?

2015-06-11 21:14 GMT+02:00 Isaac Askew <notifications@github.com>:

**Comment by ceeram** [comment]
seems the readme in 3.0 branch already has this info, you have looked at
master readme by mistake then i guess.

2015-06-11 21:41 GMT+02:00 Ceeram <c33ram@gmail.com>:

**Comment by isaacaskew** [comment]
That was exactly the issue. Thank you!

**Comment by tanka** [comment]
Hi i am getting exactly the same issue while trying to send email.  I am using cake version 2.6.4.
public function newsletter($id = null){
        if (!$this->Invoice->exists($id)) {
            throw new NotFoundException(__('Invalid invoice'));
        }
        $options = array('conditions' => array('Invoice.' . $this->Invoice->primaryKey => $id));
        $this->set('invoice', $this->Invoice->find('first', $options));
        $invoice = $this->Invoice->find('first', $options);
       
        $CakePdf = new CakePdf();

        $CakePdf->template('newsletter', 'default');
        //get the pdf string returned
        //$pdf = $CakePdf->output();
        //or write it to file directly
        $pdf = $CakePdf->write(APP . 'files' . DS . 'newsletter.pdf');
        debug($pdf); die();
        $email = new CakeEmail();
        $email->config('mandrill');
      //  $email->from('noreply@yourapp.com');
        $email->to('**************@****.com');
        $email->subject('Testing mail For Universal auto');
        $email->addAttachments(APP . 'files' . DS . 'newsletter.pdf');
        $result = $email->send('Here is some test content for the email.');
    }
I also have file (app/View/Pdf/newsletter.ctp) and Layout file app/View/Layouts/pdf/default.ctp"  Please help me out.  
Thank you
