### ISSUE TITLE
Generate many pages

### ISSUE THREAD

**Issue by deenice** [FriendsOfCake/CakePdf#109]
Hi,
Is it possible to generate one pdf with many pages (with the control of the content in each page)? I really need this and don't know how I can achieve this... Please help.

**Comment by dakota** [comment]
That depends entirely on what engine you are using. Each one has their own method, and is documented in their respective documentation.

**Comment by deenice** [comment]
I'm using wkhtmltopdf and I can't find anything relevant to do my tasks

**Comment by dakota** [comment]
[This should help](http://www.htm2pdf.co.uk/page-breaking/) :smile:

**Comment by deenice** [comment]
I will try it tomorrow! Thanks

**Comment by ceeram** [comment]
It is doable but often hard to get it done right. Often the first page
differs from all others. I might not have tried hard enough myself as for
it didn't matter too much. Good luck
Op 16 jun. 2015 18:14 schreef "Denis Bossy" <notifications@github.com>:

**Comment by deenice** [comment]
Thanks @dakota ! It works like a charm :)
