### ISSUE TITLE
cakepdf not work on cakephp 3.x

### ISSUE THREAD

**Issue by metaled** [FriendsOfCake/CakePdf#111]
I'm working with CakePHP 3.0.8 and following the steps of the documentation I can not generate pdf, please if it has been tested with this version of the framework or some missing step described in the documentation.
I'm working with the branch 3.0 of CakePdf with DomPdf engine

Thank You

**Comment by oliwerhelsen** [comment]
There is some version missmatching with dompdf. I stop trying to use dompdf and start working with mpdf.

**Comment by ADmad** [comment]
Dompdf issue has been fixed. Try out the master branch or wait until next release.
