### ISSUE TITLE
wkthmltopdf engine not working in 3.0?

### ISSUE THREAD

**Issue by burzum** [FriendsOfCake/CakePdf#112]
I'm following the instructions from https://github.com/FriendsOfCake/CakePdf/tree/3.0 to generate a pdf, the 2nd way described there to use it as email attachment.

I'm using the wk engine but it looks like the documentation isn't complete, there is a bug or i do something wrong. I have a model method that pretty much is the same as the example from the documentation.

When I run my test I'm getting:

```
Cake\Core\Exception\Exception: WKHTMLTOPDF didn't return any data
```

Debugging the command it generates has shown this:

```
C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe --quiet --print-media-type --orientation "portrait" --page-size "A4" --encoding "UTF-8" - -
```

It looks like the input file/data is missing?

**Comment by Xety** [comment]
Hi,

I had the same error and i noticed that work when the path of the executable doesn't containt any space.
*Doesn't work* :
```
C:\\Program Files (x86)\\wkhtmltopdf\\bin\\wkhtmltopdf.exe
```

*Work* :
```
C:\\wkhtmltopdf\\bin\\wkhtmltopdf.exe
```

**Comment by ADmad** [comment]
Looks like the binary path needs to be escaped when executing shell command. PR to fix it is welcome.
