### ISSUE TITLE
Passing wkhtmltopdf a url with relative links to stylesheets/scripts

### ISSUE THREAD

**Issue by alec-w** [FriendsOfCake/CakePdf#113]
When using wkhtmltopdf from the command line a url to a page that has relative links to the css/js files can used. The closest it is possible to get to this with CakePdf is by using `file_get_contents()` and then  manually going through and replacing relative stylesheet links with full ones.

Being able to use this same functionality of wkhtmltopdf through CakePdf would be very useful.

**Comment by sebtiz13** [comment]
For link relative you do set "full_base=>true" on link, css and js
But for me I have a probleme when cakephp is not on root of domain

**Comment by ADmad** [comment]
Relative urls for assets won't work, you need to use full urls.
