### ISSUE TITLE
CakePdf Does Not Install To Correct Plugin Path: Installs to `Plugin/Cakepdf`

### ISSUE THREAD

**Issue by jtyost2** [FriendsOfCake/CakePdf#115]
CakePdf when installing via composer does not install to the correct directory.

It installs to `Plugin/Cakepdf` as opposed to the valid `Plugin/CakePdf`

I built a simple test repo https://github.com/jtyost2/cakepdf-test that essentially duplicates the `composer.json` for `FriendsOfCake/CakePdf` and when loading this repo, the path is correctly set to `Plugin/CakePdf`

I can correct this issue by setting a custom install path for the plugin in my `composer.json` like so

```json
"extra": {
    "installer-paths": {
      "Plugin/CakePdf": ["friendsofcake/cakepdf"]
    }
}
```

Video of `composer require`ing `FriendsOfCake/CakePdf` and being installed to the incorrect path vs. `require`ing `jtyost2/cakepdf-test` and being installed in the correct path: https://www.dropbox.com/s/z1l5znnwloom5qy/CakePdfNotInstalledToCorrectLocation.mov?dl=0

**Comment by ceeram** [comment]
Master branch does have the installer name set. I dont know why installer path would be needed. Im assuming we are talking about a cakephp 2.x application here? Ill try to reproduce your issue later today

**Comment by jtyost2** [comment]
Yep, it is a Cake 2 app.

**Comment by jtyost2** [comment]
And yeah, the problem is that the `installer-name` for the `composer.json` isn't set in the latest release of this plugin.

We need a new release with the `installer-name` set for this plugin.

I'm loading the latest release not the `dev-master` branch.

**Comment by beporter** [comment]
Yep that probably explains it. Anyone unfortunate enough to use a reasonable version specifier like `"friendsofcake/cakepdf": "~1.0",` will end up with a composer.json that doesn't specify the `installer-name`.

Is there any change of getting a new tag released?

**Comment by ceeram** [comment]
Will do
Op 14 jul. 2015 21:46 schreef "Brian Porter" <notifications@github.com>:

**Comment by ceeram** [comment]
1.0.3 was released

**Comment by beporter** [comment]
Thank you! :+1:
