### ISSUE TITLE
Having same template and layout files for both serving as view and writing the PDF

### ISSUE THREAD

**Issue by Spriz** [FriendsOfCake/CakePdf#116]
Hi!

I'm having a use-case where customers can access a "form" as a PDF with /forms/view/form_id.pdf - and see this specific form's pdf view - but besides this they can also choose to save this pdf-file to their dropbox - to make this happen, do you really need to have 2 similar set of templates files and layout files?

Using cake 3

**Comment by Spriz** [comment]
Is it just me, or do you really need 2 set similar template and layout files?

**Comment by Spriz** [comment]
Any news on this one? Is there a reason you aren't allowed to set this eg. https://github.com/FriendsOfCake/CakePdf/blob/master/src/Pdf/CakePdf.php#L813 by config rather than hardcoded "pdf" ? :smile:

**Comment by ADmad** [comment]
You can set `$this->viewBuilder()->layoutPath()` and `$this->viewBuilder()->templatePath()`.

**Comment by Spriz** [comment]
Yes, thanks - I PR'ed that myself :D Sorry for not closing issue though...
