### ISSUE TITLE
Error in PDF

### ISSUE THREAD

**Issue by FelipeMenezes** [FriendsOfCake/CakePdf#119]
When generating the PDF displays the following error:
=> wkhtmltopdf binary is not found or not executable: / usr / bin / wkhtmltopdf

Could you help me

**Comment by tiago-gomes** [comment]
Hello Felipe.

1 -Did you installed wkhtmltopdf in your Linux Distribution?
2 -Did you applied the binary parameter in your config?

Example: 
Configure::write('CakePdf', array(
	'engine' => 'CakePdf.WkHtmlToPdf',
	'binary' => '/usr/bin/wkhtmltopdf',
	 'options' => array(
            'print-media-type' => false,
            'outline' => true,
            'dpi' => 96
        ),
        'margin' => array(
            'bottom' => 15,
            'left' => 50,
            'right' => 30,
            'top' => 45
        ),
        'orientation' => 'Portrait',
        'download' => false
));

**Comment by FelipeMenezes** [comment]
Hello Tiago,

In the Windows environment, I made the project run. However on Linux displays the following message: WKHTMLTOPDF didn't return any data.

Already enter the correct path: protected $ binary = '/ usr / bin / wkhtmltopdf';
