### ISSUE TITLE
Cakepdf output results in a 404 Not Found

### ISSUE THREAD

**Issue by tiago-gomes** [FriendsOfCake/CakePdf#120]
The server seams to be responding 404 HTTP on any request to the pdf url, which results in an error for the Chrome pdf viewer.

GET /orders/pdf/252.pdf HTTP/1.1
Host: www.example.com
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, sdch
Accept-Language: pt-PT,pt;q=0.8,en-US;q=0.6,en;q=0.4,es;q=0.2,fr;q=0.2
Cookie: _ga=GA1.2.1218083118.1428360710; CakeCookie[lang]=usa; www_example_com=58huo5dn2ulbklebdug1su5gr6
DNT: 1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36

HTTP/1.1 404 Not Found
Connection: keep-alive
Content-Length: 14031
Content-Type: application/pdf
Date: Sun, 23 Aug 2015 14:48:11 GMT
Server: nginx

**Comment by ADmad** [comment]
There's nothing we can do to help. You need to figure out the cause of 404.
