### ISSUE TITLE
Problem with css and variables

### ISSUE THREAD

**Issue by darkglamb** [FriendsOfCake/CakePdf#121]
Hi, i've installed CakePdf (3.0 branch) on my "CakePhp 3.1.0-beta2", now if i try to include some css in my pdf template CakePhp report some error like:

>[Cake\View\Exception\MissingHelperException] Helper class autoLayoutHelper could not be found. #0 /var/www/fattura.click/blog/vendor/cakephp/cakephp/src/Core/ObjectRegistry.php(91): Cake\View\HelperRegistry->_throwMissingClassError('autoLayout', NULL) #1 /var/www/fattura.click/blog/vendor/cakephp/cakephp/src/View/HelperRegistry.php(67): Cake\Core\ObjectRegistry->load('autoLayout') #2 /var/www/fattura.click/blog/vendor/cakephp/cakephp/src/View/View.php(840): Cake\View\HelperRegistry->__isset('autoLayout') #3 /var/www/fattura.click/blog/vendor/cakephp/cakephp/src/View/View.php(567): Cake\View\View->__get('autoLayout') #4 /var/www/fattura.click/blog/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(337): Cake\View\View->render('error500', 'error') #5 /var/www/fattura.click/blog/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(319): Cake\Error\ExceptionRenderer->_outputMessageSafe('error500') #6 /var/www/fattura.click/blog/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(180): Cake\Error\ExceptionRenderer->_outputMessage('error500') #7 /var/www/fattura.click/blog/vendor/cakephp/cakephp/src/Error/ErrorHandler.php(145): Cake\Error\ExceptionRenderer->render() #8 /var/www/fattura.click/blog/vendor/cakephp/cakephp/src/Error/BaseErrorHandler.php(156): Cake\Error\ErrorHandler->_displayException(Object(Cake\Core\Exception\Exception)) #9 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Cake\Core\Exception\Exception)) #10 {main} 
File /var/www/fattura.click/blog/vendor/cakephp/cakephp/src/Error/ErrorHandler.php 

i've also some problem with variables if i do:
> $this->set('variable', $variable);

in my view function in the pdf i can't see the variable "$variable"

**Comment by darkglamb** [comment]
ok, some update, reverting cakephp to 3.0.12 now I do not get more errors but still does not load the CSS file and the variables

**Comment by edsonmgoz** [comment]
Please tell me if you tried the plugin in CakePHP 3.x with DomPdf engine because it has my not work for me.
Thank You

**Comment by ADmad** [comment]
Issue with incorrect namespace for dompdf is fixed. You can try the master branch or wait for release.
