### ISSUE TITLE
CakePdf for Cakephp3

### ISSUE THREAD

**Issue by rogeriorps** [FriendsOfCake/CakePdf#127]
Congratulations for this awesome project.
I have tried to install it on Cakephp3 but seems that some configuration are a bit different. I have found some people also trying to install it but without success. 
Is it possible to write a documentation with more details focusing on Cakephp3? It will help lots of users.
Thanks,
Rogerio

**Comment by sebtiz13** [comment]
Hello
What is your error ?

**Comment by moretty** [comment]
With domPDF it's just crashing at the beggining... 

"undefined function explode_url()"

**Comment by sierrakilo** [comment]
Hi,

Yes I have also been unable to make this work in 3.1. Regardless of whether I have /controller/action/id or /controller/action/id.pdf it assumes just a html page and ignores the pdf.

I did a debug on $this->request and got:

    '_ext' => null,
    'pass' => [
        (int) 0 => '1.pdf'
    ]

which I am not sure is relevant but may help with sourcing the problem.

**Comment by oliwerhelsen** [comment]
Anyone solved this problem: Fatal error: Call to undefined function explode_url() in /var/www/public/vendor/dompdf/dompdf/include/stylesheet.cls.php on line 147

Grateful for a solution on this one:)

**Comment by dereuromark** [comment]
Seems related to https://github.com/FriendsOfCake/CakePdf/pull/153

**Comment by ADmad** [comment]
Closing as PR #153 to update docs has been opened.
