### ISSUE TITLE
CSS Classes not working for "footer-html"

### ISSUE THREAD

**Issue by SchuD** [FriendsOfCake/CakePdf#130]
Hello,
I am using your cakepdf implementation but have some issues regarding the style of the footer. The implementation of the footer-html looks like the following.

```
$this->pdfConfig = array(
   'orientation' => 'portrait',
   'filename' => 'Report',
    'options' => [
        'footer-html' => Router::url('/', true).'webroot/files/footer.html'
      ]
      );
```

The data from footer.html is printed out at the foot of the page but none of the css classes are working. Therefore I include a head-tag with some css classes to let the footer look pretty. But as soon as I use a head tag with a css class, the footer is going to the top of the page und uses the whole page minus a few pixels for the footer. The result is, that I do have a nice footer but with 20 pages of estimated 20px content per page. 
Is it possible to give the footer some classes or to directly say that the footer uses the classes of the default page?

**Comment by aguirre1017** [comment]
Im encountering the error below using this plugin in cakephp 3.0 project.

What seems to be the problem? I followed all the configuration on the docs.

```
Fatal error: [Cake\View\Exception\MissingTemplateException] Template file "Error\pdf\error500.ctp" is missing. #0 D:\xampp\htdocs\vendor\cakephp\cakephp\src\View\View.php(576): Cake\View\View->_getViewFileName('error500') #1 D:\xampp\htdocs\vendor\friendsofcake\cakepdf\src\View\PdfView.php(117): Cake\View\View->render('error500', 'error') #2 D:\xampp\htdocs\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(358): CakePdf\View\PdfView->render('error500', 'error') #3 D:\xampp\htdocs\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(327): Cake\Error\ExceptionRenderer->_outputMessageSafe('error500') #4 D:\xampp\htdocs\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(329): Cake\Error\ExceptionRenderer->_outputMessage('error500') #5 D:\xampp\htdocs\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(194): Cake\Error\ExceptionRenderer->_outputMessage('fatalError') #6 D:\xampp\htdocs\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(144): Cake\Error\ExceptionRenderer->render() #7 D:\xampp\htdocs\vendor\cakephp\c in D:\xampp\htdocs\vendor\cakephp\cakephp\src\Error\ErrorHandler.php on line 156
```
