### ISSUE TITLE
Composer installation problem

### ISSUE THREAD

**Issue by Ginopinoshow** [FriendsOfCake/CakePdf#132]
While I try to install CakePdf with composer update, it say tha package could not be found

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

      Problem 1
        - The requested package friendsofcake/cakepdf could not be found in any version, there may be a typo in the package name.
    
    Potential causes:
     - A typo in the package name
     - The package is not available in a stable-enough version according to your minimum-stability setting
       see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
    
    Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by oliwerhelsen** [comment]
Hey,

Use this: "friendsofcake/cakepdf": "^3.1",

**Comment by moumene23** [comment]
#Ginopinoshow  did you resolve it ?
oliwerhelsen how to add it ...i just add it and same message as Ginopinoshow appear ! so ?

**Comment by Ginopinoshow** [comment]
Yea, with "friendsofcake/cakepdf": "^3.1" works, thanks @oliwerhelsen
