### ISSUE TITLE
Could not render cell 

### ISSUE THREAD

**Issue by hstorm** [FriendsOfCake/CakePdf#134]
Hi, I want to use cake "Cells" in a pdf view.

I created a Cell as described here http://book.cakephp.org/3.0/en/views/cells.html
Rendering the cell works find in any "normal" view. However, when rendering the cell in a pdf view the following error occurs.  

When using in the view 
           <?php    $cell = $this->cell('Bill'); ?>
and 
          <?= $cell ?>
The following error occurs:
"Warning (512)
: Could not render cell - Cell view file "display" is missing. [CORE\src\View\Cell.php, line 233]"

When using  <?= $cell->render() ?> to render the cell a fatal error occurs:

Fatal error: [Cake\View\Exception\MissingTemplateException] Template file "Error\pdf\error500.ctp" is missing. #0 C:\xampp\htdocs\topti\vendor\cakephp\cakephp\src\View\View.php(576): Cake\View\View->_getViewFileName('error500') #1 C:\xampp\htdocs\topti\vendor\friendsofcake\cakepdf\src\View\PdfView.php(117): Cake\View\View->render('error500', 'error') #2 C:\xampp\htdocs\topti\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(340): CakePdf\View\PdfView->render('error500', 'error') #3 C:\xampp\htdocs\topti\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(309): Cake\Error\ExceptionRenderer->_outputMessageSafe('error500') #4 C:\xampp\htdocs\topti\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(311): Cake\Error\ExceptionRenderer->_outputMessage('error500') #5 C:\xampp\htdocs\topti\vendor\cakephp\cakephp\src\Error\ExceptionRenderer.php(180): Cake\Error\ExceptionRenderer->_outputMessage('fatalError') #6 C:\xampp\htdocs\topti\vendor\cakephp\cakephp\src\Error\ErrorHandler.php(144): Cake\Error\ExceptionRenderer->re in C:\xampp\htdocs\topti\vendor\cakephp\cakephp\src\Error\ErrorHandler.php on line 156

Any suggestions what could causes the problem?
 
Thanks! Hugo

**Comment by ADmad** [comment]
As the error states you are missing the view file for the template.
