### ISSUE TITLE
.pdf extension or not issues

### ISSUE THREAD

**Issue by Spriz** [FriendsOfCake/CakePdf#135]
Hi! 

I'm having some weird issues with CakePdf and url extensions. Somewhere in our app we use pdf extension, while somewhere we just used to render .pdf even without the extensions, depending on the logic behind the controller - but that doesn't seem possible anymore :-(

With 3.1 only thing I need to do to generate a PDF is to include `$this->viewBuilder()->className('CakePdf.Pdf');` - but then it doesn't work if I append .pdf to the URL (`Fatal DOMPDF_Exception Frame not found in cellmap`)

It's a relatively easy fix:
```
if (!$this->request->param('_ext') !== 'pdf') {
            $this->viewBuilder()->className('CakePdf.Pdf');
        }
```

But I'm wondering if I'm doing something wrong here? :yum:

**Comment by ADmad** [comment]
Check the latest readme to ensure proper configuration so that using `.pdf` extension works as expected.
