### ISSUE TITLE
Unoconv Support

### ISSUE THREAD

**Issue by ionas** [FriendsOfCake/CakePdf#139]
Any chance:
https://github.com/alchemy-fr/PHP-Unoconv
https://github.com/dagwieers/unoconv
http://dag.wiee.rs/home-made/unoconv/

?

**Comment by ADmad** [comment]
I haven't  heard of unoconv before, looks like a tool to convert files from one format to another. What kind of support for it do you expect in this plugin?

**Comment by jhli** [comment]
It is basically the libreoffice converter which can for instance export open document formats (some open standard xml based document formats) and html (!) to pdf.

**Comment by jhli** [comment]
http://dag.wiee.rs/home-made/unoconv/

**Comment by jhli** [comment]
Basically you would feed it xml compatible html/css and it would return pdfs.

**Comment by dereuromark** [comment]
That sounds like something that could be supported, given that someone provides a PR.

**Comment by jhli** [comment]
When I get to replace my ZendPDF Based hacks I ll prob do a PR - but thats not even on my schedule at the moment, so can't promise.

**Comment by ADmad** [comment]
Closing due to lack of interest.
