### ISSUE TITLE
PdfView should extend AppView

### ISSUE THREAD

**Issue by dereuromark** [FriendsOfCake/CakePdf#145]
Currently PdfView is not extending AppView, and thus never calling the initialize() method with all helper load calls.
Since 3.x now advertises to load helpers in AppView instead of Controller level, we should really extend this view.

Currently I have missing helper exceptions because of this, and I cannot really load those now in a global place.

**Comment by dereuromark** [comment]
PR open.

**Comment by waspinator** [comment]
until this gets resolved, is there a way to load helpers without extending AppView in cakepdf?
