### ISSUE TITLE
Router::extensions(['pdf']) not respected

### ISSUE THREAD

**Issue by dereuromark** [FriendsOfCake/CakePdf#147]
using routes=>true on Plugin::load() should enable pdf as extension.
So I only have Router::extensions(['json']); in my own app routes.php because those should be merged.
And debugging the CakePdf routes.php file shows: They are merged:
```
[
	(int) 0 => 'json',
	(int) 1 => 'pdf'
]
```

But then, the controller does not work:

    The action action.pdf is not defined in DemoController

It seems something in 3.1 goes wrong here regarding extension handling in routes.
I suspect that the routes parsing happens before the extensions could all be set when relying on plugin routes.php files.

**Comment by ndm2** [comment]
`Router::scope()` reads the currently set global extensions and passes them on into the route builder, and from there on the global extensions aren't touched anymore. That means that the `Router::plugins()` call which in the app template is by default placed after the route definitions, comes too late.

AFAIR that's not a 3.1 specific problem, it was always like that, as it's a feature so that global extensions cannot randomly "pollute" routes.

**Comment by dereuromark** [comment]
In that case https://github.com/FriendsOfCake/CakePdf/blob/master/config/routes.php#L4 is highly misleading and should be removed.

**Comment by ndm2** [comment]
I would have suggested that too. In any case an explanation would be required in the docs, so promoting the "correct", manual approach of adding extensions is probably the way to go (not sure if one could call moving the `Router::plugins()` call upwards "wrong", but it could certainly in turn introduce other problems).

**Comment by Isengo1989** [comment]
So is there an solution for this problem? I already "wasted" more then 10 hours in that issue.

**Comment by ndm2** [comment]
Call me again after 72 hours of no sleep, no food, and no water, when you're one step away from setting your computer on fire and chopping it into pieces with a rabid weasel tied to a spiked mace, you're not real developer until then :)

On a serious note, check the updated readme: https://github.com/ndm2/CakePdf/blob/ffbeddfccb61f57262248fe5ab8de3769fedb34b/README.md#setup

**Comment by Isengo1989** [comment]
OMG! This works! I had it at the end at some desperate point......

Thanks so much! I am flipping my shit!

**Comment by ADmad** [comment]
Closing as PR #153 is open to update readme.
