### ISSUE TITLE
Install with require

### ISSUE THREAD

**Issue by Isengo1989** [FriendsOfCake/CakePdf#149]
Everytime I install the plugin with composer.json it deinstalls my ADmad Plugin for I18n

Any ideas?

**Comment by dereuromark** [comment]
How do you install it etc?
You need to be more specific and verbose.

**Comment by Isengo1989** [comment]
I am using "composer require friendsofcake/cakepdf" after this did not work I reverted the changes with my IDE and used the composer.json with both Plugins in it and the require Syntax.
