### ISSUE TITLE
CakePdf won´t load PDF

### ISSUE THREAD

**Issue by Isengo1989** [FriendsOfCake/CakePdf#151]
So, I got it running without any error now. But I can´t create any .pdf File, nor download one. I try to be specific as much as possible.

I have my InvoicesController

```
<?php
namespace App\Controller;


class InvoicesController extends AppController
{



    // In your Invoices controller you could set additional configs, or override the global ones:
    public function view($id)
    {

        $this->pdfConfig = array(
            'orientation' => 'landscape',
            'download' => true,
            'filename' => 'invoucne.pdf'

        );
    }

    public function view2() {
        // .....
        return $this->render('pdf/view', 'pdf/default');
    }

}
?>
```

Also I´ve added already my Requesthandler to my AppCpntroller. My Layout and Invoices Folder in Template contains a pdf Folder with default and view.ctp

My Plugins lay in vendor (dompdf and friendsofcake) and I don´t get any error.

I am calling "http://localhost/caketest/invoices/view2/1.pdf"

Thanks in advance. I don´t know how I can solve it.

**Comment by Isengo1989** [comment]
You sell support? I am sick and I need it working...

**Comment by ndm2** [comment]
#147 probably...

**Comment by TristanMAC** [comment]
Isengo1989 is this working yet?

I was having the same results as above, and I realized I did not yet have the .pdf extension enabled within my config/routes.php

I have requested they add this step to the Readme.md hopefully they do as it will save a lot of people trouble

config/routes.php

`
Router::scope('/', function ($routes) {
	$routes->extensions(['pdf']);

//other code here
}
`

**Comment by Isengo1989** [comment]
Yes, it did indeed solve my problem and they put it in the docs now. I had it in there for a while, but not above the routes, which was my problem...

**Comment by ndm2** [comment]
Actually it's not yet up, but hopefully it will be soon #153
