### ISSUE TITLE
Add support for wrapper scripts for wkhtmltopdf

### ISSUE THREAD

**Issue by nrother** [FriendsOfCake/CakePdf#155]
I need to run `wkhtmltopdf` wrapped in `xvfb-run`, but this is currently not possible. A `wrapper-binary` option would be useful in this case.

**Comment by nrother** [comment]
PR in #156

**Comment by ADmad** [comment]
https://github.com/FriendsOfCake/CakePdf/issues/189#issuecomment-277277998
