### ISSUE TITLE
EventManager Class not found

### ISSUE THREAD

**Issue by 2810rohit** [FriendsOfCake/CakePdf#158]
Hi, i am using CakePHP 2.6 version

getting below error 

Fatal error: Class 'Cake\Event\EventManager' not found in /var/www/html/project/app/Plugin/CakePdf/Config/bootstrap.php on line 4
Class 'Cake\Event\EventManager' not found

**Comment by binhtrang** [comment]
Hi, Could you help me this problem? How to Cakephp 2.6 version understand define 'Cake\Event\EventManager" ?

**Comment by themrwilliams** [comment]
@2810rohit @binhtrang - CakePdf requires CakePHP 3x and you both say that you're using 2.

You could try looking at the 1x branch of the plugin (e.g., https://github.com/FriendsOfCake/CakePdf/tree/1.0.3) but it's probably unsupported.
