### ISSUE TITLE
“Wkhtmltopdf didn't return any data” with CakePHP

### ISSUE THREAD

**Issue by SchuD** [FriendsOfCake/CakePdf#160]
I am running a CakePHP 2.8 environment and want to print a PDF with wkhtmltopdf. Once, I could create an PDF, then, I didn't used it for few weeks because I was working on something else. Today I restarted to work on that and got the error Message:

```
"WKHTMLTOPDF didn't return any data" 

APP/Plugin/CakePdf/Pdf/CakePdf.php line 236 → WkHtmlToPdfEngine->output()
APP/Plugin/CakePdf/View/PdfView.php line 97 → CakePdf->output(string)
CORE/Cake/Controller/Controller.php line 963 → PdfView->render(null, null)
CORE/Cake/Routing/Dispatcher.php line 200 → Controller->render()
CORE/Cake/Routing/Dispatcher.php line 167 → Dispatcher->_invoke(InvoicesController, CakeRequest)
APP/webroot/index.php line 109 → Dispatcher->dispatch(CakeRequest, CakeResponse)
```

My machine is a MacBook Pro with El Capitan. Furthermore, I thought that it might be the El Capitan Update, but then I installed wkhtmltopdf to an equal system with CakePHP 2.8 and it is running on this machine. Unfortunately, I have no idea what I can do. I reinstalled wkhtml and updated CakePHP again, but no chance :-(

**Comment by SchuD** [comment]
Finally, I did it. I first deleted all wkhtmltopdf /img files on usr/local/bin and then changed the wkthmltopdf from 64bit to 32bit. Although I have a 64bit system, it is working with the 32bit but not the 64bit. Don't ask me why it is working, but it works for me!

**Comment by assisjeferson** [comment]
@SchuD Where you changed for use the 32bit? I'm having the same problem :/

**Comment by SchuD** [comment]
After deleting the 64bit version, I just downloaded the 32bit version and installed that. That was it.
