### ISSUE TITLE
chronos issue in CakePDF

### ISSUE THREAD

**Issue by anujshsdei** [FriendsOfCake/CakePdf#161]
Hi

I am working on project which is under development and I am using the cakephp version 3.1.6, and for pdf generation I am using the cakePDF. I setup the plugin as mentioned in https://github.com/FriendsOfCake/CakePdf and still not able to generate the PDF.

When I tried to create the PDF it throws the error Class DateTimeImmutable not found. 

I searched in the file directory where I found the folder chronos in vendor/cakephp/chronos. This folder is created I guess after running the 

composer require dompdf/dompdf
composer require tecnick.com/tcpdf
composer require mpdf/mpdf

I am using tcpdf for pdf generation. Please help.

Thanks

**Comment by ADmad** [comment]
> it throws the error Class DateTimeImmutable not found

You need PHP 5.5 or above.
