### ISSUE TITLE
Image is not showing on pdf ?

### ISSUE THREAD

**Issue by designskiller** [FriendsOfCake/CakePdf#162]
Hey There,
I  using cakePDF wkhtmltopdf engine all data is working fine but image is not showing. 
Please help me.

Thanks in advance.

**Comment by ADmad** [comment]
Ensure you are using absolute urls as stated in [readme](https://github.com/FriendsOfCake/CakePdf#note-about-static-assets).

**Comment by designskiller** [comment]
Yeah i got this am not using an absolute URL.

Thanks.
