### ISSUE TITLE
Errors without layout

### ISSUE THREAD

**Issue by djonatanb** [FriendsOfCake/CakePdf#164]
I just wanted to point out that I went through a pickle when I tried to just run it for a test with a completely empty layout. 

I kept getting the error  Template file "Pdf/.ctp" is missing 

this is the output I got:

https://gist.github.com/djonatanb/590323e6c97111663f64

**Comment by ADmad** [comment]
Did you set layout to empty string?

**Comment by djonatanb** [comment]
I had the layout file at Layouts/pdf/default.ctp but there was nothing inside it, just a blank file.
I didn't set anything else, not even the fetch content. Until I later realized that. But still was just a fast run to see if it was properly configured and etc.
