### ISSUE TITLE
Debug the html before writing the pdf file

### ISSUE THREAD

**Issue by flashios09** [FriendsOfCake/CakePdf#166]
Hi,
I want to debug the html(view the result in browser) before writing the pdf file, creating the file and close/re-open it to see the result is **annoying**(+ waste of time).
To do that i have to use the `CakePdf::_render()` method:
```php
// controller test action
public function test(){
	$CakePdf = new \CakePdf\Pdf\CakePdf();
	$CakePdf->viewRender('App\View\AppView'); 
    $CakePdf->template('test', 'default');
    $CakePdf->viewVars($this->viewVars);

    $html = $CakePdf->_render();
    $this->response->body($html);

    return $this->response;
}
```
The `_render` method is `protected` so i can't access to it :
`protected function _render()`

Is it possible to change it `public` or create another public method that we can use to get the rendered html, something like the `output` method:
```php
// CakePdf.php::getRenderedHtml
public function getRenderedHtml()
{    
    $Engine = $this->engine();
    if (!$Engine) {
        throw new Exception(__d('cake_pdf', 'Engine is not loaded'));
    }

    return $this->_render();
}
```
So instead of calling `$CakePdf->output()` we call `$CakePdf->getRenderedHtml()`

**Comment by ADmad** [comment]
> before writing the pdf file, creating the file and close/re-open it to see the result is annoying(+ waste of time).

Why do you need do that when recent versions of chrome and firefox can directly show pdfs?

**Comment by flashios09** [comment]
@ADmad 
1- If i use the wkhtmltopdf engine, i will be sure(99%) that the final result will be the same as the rendered html in the browser(don't have to refresh the browser after every css changes). 

2- Usage: 
> 2: Create PDF for email attachment, file storage etc.

So i'm using the `src/Template/Pdf/test.ctp` as a **view** and `src/Template/Layout/pdf/default.ctp` as a **layout**.

**Comment by ADmad** [comment]
I don't understand why you want to see the html only when you can just as easily see the generated pdf itself.

Anyway you easily see the html too already but doing exactly the same thing that you would to render a html page. Just need to change the template and layout paths.  Change your test method to:

```php
public function test() {
    $this->viewBuilder->templatePath('pdf');
    $this->viewBuilder->layoutPath('pdf');
    $this->render('test', 'default'); //your $this->viewVars will be actually used.
}
```

It's actually lesser code then your example :)

**Comment by flashios09** [comment]
@ADmad I want to see the generated html in browser:
1- debug(see the errors ...)
2-stylize(css) without writing the file and close/re-open it after every change

I have already extended the CakePdf.php (MyCakePdf.pdf) and overwrite some default config(like the $_viewRender property, viewVars() method, add the getRenderedHtml to be able to access to the _render() protected method).
Thanks
