### ISSUE TITLE
Passing the options to wkhtmltopdf engine

### ISSUE THREAD

**Issue by flashios09** [FriendsOfCake/CakePdf#167]
Hi,
I want to set the **margin**(top, right, bottom, left) to **0**, then adding a **background color**(using css).
Writing the pdf file via the **wkhtmltopdf** give me a perfect result(the same rendered html on **google chrome**)
```sh
wkhtmltopdf -T 0 -R 0 -B 0 -L 0 http://localhost:3000/MyController/test test.pdf
```
Using the CakePdf plugin with the **wkhtmltopdf** engine add a default margin to the generated pdf file even if i set the margin to 0 in the CakePdf config array:
```php
return [
	// CakePdf plugin
	'CakePdf' => [
	    'engine' => [
	        'className' => 'CakePdf.WkHtmlToPdf',
	        'binary' => '/usr/local/bin/wkhtmltopdf',
	        'options' => [
	            'margin-top' => 0,
	            'margin-right' => 0,
	            'margin-bottom' => 0,
	            'margin-left' => 0,
	        ]
	    ]
	]
];
```
I tried this also:
```php
return [
	// CakePdf plugin
	'CakePdf' => [
	    'engine' => [
	        'className' => 'CakePdf.WkHtmlToPdf',
	        'binary' => '/usr/local/bin/wkhtmltopdf',
	    ]
        'margin' => [
            'top' => 0,
            'right' => 0,
            'bottom' => 0,
            'left' => 0,
        ]
	]
];
```
Always the same result, like we **ignore the margin options**(--margin-top 0, ...) when **executing** the **wkhtmltopdf** command !

**Comment by ADmad** [comment]
You can debug the command generated by `WkHtmlToPdfEngine::_getCommand()` and see what's up. (Just stick a debug() and die or log the command string at appropriate location in the engine class).

**Comment by flashios09** [comment]
@ADmad before of all, using the **wkhtmltopdf** engine, **to pass options**, i have to do this:
```php
'engine' => [
    'className' => 'CakePdf.WkHtmlToPdf',
    'binary' => '/usr/local/bin/wkhtmltopdf',
    'options' => [
        'margin-top' => 0,
        'margin-right' => 0,
        'margin-bottom' => 0,
        'margin-left' => 0,
    ]
]
```
or this:
```php
'engine' => [
    'className' => 'CakePdf.WkHtmlToPdf',
    'binary' => '/usr/local/bin/wkhtmltopdf',
]
'margin' => [
    'top' => 0,
    'right' => 0,
    'bottom' => 0,
    'left' => 0,
]
```

**Comment by ADmad** [comment]
Try both and see :)

**Comment by flashios09** [comment]
@ADmad 
Inside the `WkHmlToPdfEngine.pdf::output`, i add at the top ```debug($this->_getCommand()); die();```
that's the result of the debug
```
/vendor/friendsofcake/cakepdf/src/Pdf/Engine/WkHtmlToPdfEngine.php (line 36)
'/usr/local/bin/wkhtmltopdf --quiet --print-media-type --orientation 'portrait' --page-size 'A4' --encoding 'UTF-8' - -'
``` 
I tried both like you said, the margin options doesn't exist in the generated command !

**Comment by flashios09** [comment]
I add a debug of $margin **WkHtmlToPdfEngine.php::105** ```$margin = $this->_Pdf_margin()``` , it returns this result
```
/vendor/friendsofcake/cakepdf/src/Pdf/Engine/WkHtmlToPdfEngine.php (line 106)
[
	'bottom' => null,
	'left' => null,
	'right' => null,
	'top' => null
]
```

**Comment by ADmad** [comment]
Try using:

```php
return [
    // CakePdf plugin
    'CakePdf' => [
        'engine' => [
            'className' => 'CakePdf.WkHtmlToPdf',
            'binary' => '/usr/local/bin/wkhtmltopdf',
            'margin' => [
                'top' => 0,
                'right' => 0,
                'bottom' => 0,
                'left' => 0,
            ]
        ]
    ]
];
```

**Comment by flashios09** [comment]
@ADmad same result, the options always ignored !
```
/vendor/friendsofcake/cakepdf/src/Pdf/Engine/WkHtmlToPdfEngine.php (line 36)
'/usr/local/bin/wkhtmltopdf --quiet --print-media-type --orientation 'portrait' --page-size 'A4' --encoding 'UTF-8' - -'
```

**Comment by ADmad** [comment]
You'll have to walk through the code and figure out where things go wrong. Btw just trying with margin values `1` instead of `0`. I suspect a loose empty check is causing the problem.

**Comment by flashios09** [comment]
@ADmad 
the problem is the margin() method, it always set the margin(for the 4 corners) to null using the $_marginBottom property(same thing for $_marginTop, $_marginLeft, $_marginRight)
So i overwrite this properties inside MyCakePdf.php and set their default values to 0 instead of null and now when i debug the generated command i have the --margin-top(left,right,bottom) options with 0 value.
That's solve my problem but i didn't figure out why the margin array inside the CakePdf config array is always ignored !
Thanks

**Comment by ADmad** [comment]
Would be nice if you can fix the problem and submit a patch.

**Comment by flashios09** [comment]
@ADmad I will try ;)

**Comment by ADmad** [comment]
I found the problem.

**Comment by flashios09** [comment]
@ADmad sorry this doesn't fix the problem :(
The problem isn't with the positive margin values (>0), this is work even before your last fix
The options --margin will be ignored only if we set it to 0 
that's a debug of `$this->_getCommand()` with a positive margin values:
```
'engine' => [
    'className' => 'CakePdf.WkHtmlToPdf',
    'binary' => '/usr/local/bin/wkhtmltopdf',
    'options' => [
        'margin-top' => 10,
        'margin-right' => 10,
        'margin-bottom' => 10,
        'margin-left' => 10,
    ]
]
/vendor/friendsofcake/cakepdf/src/Pdf/Engine/WkHtmlToPdfEngine.php (line 36)
'/usr/local/bin/wkhtmltopdf --quiet --print-media-type --orientation 'portrait' --page-size 'A4' --encoding 'UTF-8' --margin-top '10' --margin-right '10' --margin-bottom '10' --margin-left '10' - -'
```
if we set the margin options to 0:
```
'engine' => [
    'className' => 'CakePdf.WkHtmlToPdf',
    'binary' => '/usr/local/bin/wkhtmltopdf',
    'options' => [
        'margin-top' => 0,
        'margin-right' => 0,
        'margin-bottom' => 0,
        'margin-left' => 0,
    ]
]
/vendor/friendsofcake/cakepdf/src/Pdf/Engine/WkHtmlToPdfEngine.php (line 36)
'/usr/local/bin/wkhtmltopdf --quiet --print-media-type --orientation 'portrait' --page-size 'A4' --encoding 'UTF-8' - -'
```

**Comment by ADmad** [comment]
Use 
```php
'engine' => [
    'className' => 'CakePdf.WkHtmlToPdf',
    'binary' => '/usr/local/bin/wkhtmltopdf',
]
'margin' => [
    'top' => 0,
    'right' => 0,
    'bottom' => 0,
    'left' => 0,
]
```

**Comment by flashios09** [comment]
@ADmad 
'margin' inside/outside of the 'engine' array is always **ignored**(even with positive values).
'options' inside the 'engine' array **works only** with positive values.

**Comment by ADmad** [comment]
@flashios09 Are you checking using the master branch?  The config array i showed above will definitely work.

**Comment by flashios09** [comment]
@ADmad I updated the plugin using composer(from 3.1.0 to 3.1.1)
As i said before the problem is always with the 0 value not with positive values.

**Comment by ADmad** [comment]
I said **master**.

**Comment by flashios09** [comment]
It works, thanks @ADmad

**Comment by elriri35** [comment]
How can i get this feat ? Sorry but i'm novice.

I used composer to install cakepdf.

I can get pdf files but can't set footer html.
