### ISSUE TITLE
failed to load pdf document

### ISSUE THREAD

**Issue by ahsankhan201** [FriendsOfCake/CakePdf#173]
Hi,
My cakephp version is 3.0
I download your code in my plugin directory..  ROOT/plugins/CakePdf/config
this code is in my routs.php 
`Router::extensions(['pdf']);`
This code is in my bootstrape.php
`Plugin::load('CakePdf', ['bootstrap' => true, 'routes' => true]);
Configure::write('CakePdf', [
    'engine' => 'CakePdf.WkHtmlToPdf',
    //'binary' => 'C:\\ProgramFiles\\wkhtmltopdf\\bin\\wkhtmltopdf.exe'
    'options' => [
        'print-media-type' => false,
        'outline' => true,
        'dpi' => 96
    ],
    'orientation' => 'landscape',
    'download' => true
]);`

But when i open the url order.pdf
it shows a box with message "failed to load pdf document"
I have a default.ctp file under Templates/Layouts/pdf/
i have a view file under Templates/Orders/pdf/index.ctp

Kindly help me where i am doing mistake
and kindly tell me how can i configure it on share hosting.

Thanks

**Comment by hareshpatel1990** [comment]
I have same problem.... Can anyone resolve it?

**Comment by ADmad** [comment]
It most likely means the PDF was not generated due to PHP error. Check your error logs and/or trying opening the pdf in a text editor and see if PHP errors are shown.
