### ISSUE TITLE
Is CakePdf master compatible with CakePHP 3.0?

### ISSUE THREAD

**Issue by pperejon** [FriendsOfCake/CakePdf#176]
In the plugin documentation [the requirements](https://github.com/FriendsOfCake/CakePdf#requirements) are for CakePHP 3.0+ but then in composer.json [it requires ~3.1](https://github.com/FriendsOfCake/CakePdf/blob/master/composer.json#L9).

Question is: will it work with Cake 3.0? If so, please change the composer.json requirements, otherwise documentation should be updated.

Thanks a lot in advance!

**Comment by ADmad** [comment]
The `3.0.0` release was compatible with CakePHP 3.0 releases after that required 3.1+
