### ISSUE TITLE
When using View Cells each cell is generating PDF content

### ISSUE THREAD

**Issue by darensipes** [FriendsOfCake/CakePdf#178]
So I am using several view cells and noticed when I render a page with the pdf extension, a pdf is rendered but where each cell's content belongs is PDF encoded content not the actual content. Looking into it I noticed that the WkHtmlToPdf command was running multiple times, once for the main page and for each view cell as well. I was able to come up with a solution, but thought I would post as an issue because maybe there is a better way of handling this. Also, not sure if might not be an issue with this plugin but rather view cells in general.

So my solution was to extend the render method in my view cell like this:

```php
public function render($template = null)
{
    if ($this->viewBuilder()->className() == 'CakePdf\View\PdfView') {
        $this->viewBuilder()->className('Cake\View\View');
    }
    return parent::render($template);
}
```

That solved the issue. I think I was expecting this to be accounted for when rendering a page with the pdf extension.

**Comment by ADmad** [comment]
What you have done is an acceptable way to handle to handle the problem currently. A more generic solution would be enhancing the `CellTrait::cell()` to allow specifying view builder options.

**Comment by darensipes** [comment]
@ADmad  Thanks, I will look into CellTrait as well and if I come up with anything I will submit a PR to here or Cake.

**Comment by zipate** [comment]
Thanks man. I was struggling with the same error for a couple of weeks. Please submit your solution for CellTrait option as well.
