### ISSUE TITLE
How to display image and iframe embedded in generated PDF file 

### ISSUE THREAD

**Issue by WaseemAR** [FriendsOfCake/CakePdf#182]
Hi,

How to display image and iframe inside the pdf file? also is it possible to save the generated pdf in server folder rather than download the pdf?

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePdf plugin. If you are
looking for help on how to implement a feature or to better understand
how to use the plugin correctly, please visit one of the following:

[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
