### ISSUE TITLE
Cannot load mpdf engine on Shared Hosting

### ISSUE THREAD

**Issue by amendezcabrera** [FriendsOfCake/CakePdf#183]
Hi, I succesfully implemented the "mpdf" engine over my local test environment, but have errors when I upload all the files to the production server. The server is in a shared server and I don't have SSH access. I would like to know if there is anything I could do in order to get it to work? The error says "Pdf engine CakePdf.mpdf not found".
Thank you in advance

**Comment by ADmad** [comment]
The engine name is `Mpdf` so it should be looking for `CakePdf.Mpdf` not `CakePdf.mpdf`. Casing matters. This is what happens when you develop on a case insensitive OS like windows and deploy in linux which is case sensitive. Fix your casing to resolve your issue.

**Comment by amendezcabrera** [comment]
Yes, now I'm getting a "memory allocation" error so I think the problem is solved.
You are right, I hate developing in a Windows environment, it isn't the first issue related to the casing, but it is what I have at work.
Thank you very much
