### ISSUE TITLE
How to header and footer with CakePHP 3.3

### ISSUE THREAD

**Issue by thiagoreri** [FriendsOfCake/CakePdf#184]
$CakePdf = new \CakePdf\Pdf\CakePdf();
        $CakePdf->template($template, $layout);
        $CakePdf->header('dasdasdasd', 'dasdas', 'dasdasdasdasdasd');

        $CakePdf->viewVars($viewVars);
        $pdf = $CakePdf->output();

Not Working

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePdf plugin. If you are
looking for help on how to implement a feature or to better understand
how to use the plugin correctly, please visit one of the following:

[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!
