### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by tsouhaieb** [FriendsOfCake/CakePdf#187]
is there a manual way to install cakepdf and mpdf ?

**Comment by ADmad** [comment]
Probably but it's not recommended and you will have to figure out the class loading yourself. Will be much easier to just use composer.

**Comment by tsouhaieb** [comment]
i have to do it manually because the server does not give me the possibility to use composer
also when i tried to install it locally, it throw an error linked to php-intl and i'm using mamp,

this is why i want to do it manually
