### ISSUE TITLE
wkhtmltopdf binary is not found or not executable

### ISSUE THREAD

**Issue by levend18** [FriendsOfCake/CakePdf#188]
How can ı fix this problem i try alot of  solution for this.
i change   Configure:write like this but not work.
Configure::write( 'CakePdf', array(
    'engine' => 'CakePdf.WkHtmlToPdf',
    'options' => array(
        'print-media-type' => false,
        'outline' => true,
        'dpi' => 96
    ),
    'margin' => array(
        'bottom' => 15,
        'left' => 50,
        'right' => 30,
        'top' => 45
    ),
    'binary' => 'C:' . DS . 'wkhtmltopdf' . DS . 'wkhtmltopdf.exe',
    'orientation' => 'landscape',
    'download' => false
));
wkhtmltopdf binary is not found or not executable: /usr/bin/wkhtmltopdf #0 
is there any solution for this? #

**Comment by ADmad** [comment]
The 'binary' option is supposed to be nested inside the 'engine' options array. Check the example in README carefully.
