### ISSUE TITLE
Creating and sending as a email attachment - can't get to work

### ISSUE THREAD

**Issue by jamesjacobs** [FriendsOfCake/CakePdf#19]
Hi, firstly, thanks for making a great plugin. This isn't exactly an issue more that I can't get it to work and would really appreciate your help (I'm still a bit of a cake novice).

I've been trying to get this to work based on the details in the read me file but have hit a brick wall. I'm trying to create a pdf to be sent as an email attachment. I'm my controller I have this:

```
        // Build PDF as attachment
        $CakePdf = new CakePdf();
        $CakePdf->template('view', 'default');
        //get the pdf string returned
        $pdf = $CakePdf->output();

        // SMTP Options
        $this->Email->smtpOptions = array(

            // Only to be used internally
            'port'=>'25',
            'timeout'=>'30',
            'host' => '192.2.200.9',
            'username'=>'',
            'password'=>''
         );
        $this->Email->template = 'newExpenseClaim';
        $this->Email->from    = 'Expense Tracker <james@test.com>';
        $this->Email->to      = 'james.jacobs@eclipselegal.co.uk'; // This needs to be a new mailbox, like expense.admins@eclipselegal.co.uk etc
        $this->Email->subject = 'New Expense Claim Submitted - Please Review';
        $this->Email->sendAs = 'both';
        $this->Email->delivery = 'smtp';

        $this->Email->attachment = $pdf;

        // Set username & url in email
        $this->set('user', $fu['User']['name']);
        $this->set('ms', $ms);
        $this->Email->send();
        $this->set('smtp_errors', $this->Email->smtpError);
```

I seem to be failing on the first hurdle though as I get "Error: Class 'CakePdf' not found" when I run the code. I have everything set up OK in bootstrap etc as I am successfully showing views as PDFs but am struggling when trying to create one to attach to an email.

Would you mind pointing me in the right direction?

Many thanks in advance for your help.

**Comment by Govinda-Wagle** [comment]
Thank you ceeram, I have used php function like 
<?php file_put_contents('example.pdf', $base64Pdf);?>
<?php header('Content-Type: application/pdf');?>. Is it ok?

**Comment by ceeram** [comment]
That does not look correct really.Please drop by on irc if you can, this is
not really the place for support, as this is a bug tracker.

2015-01-09 14:51 GMT+01:00 Govinda Wagle <notifications@github.com>:

**Comment by parixit572** [comment]
It's old thread but I wanted to do same functionality as @jamesjacobs wanted. Below is my code. I have "WkHtmlToPdf" engine enabled with valid binary path given.

When I try to generate and open/download PDF in browser using same engine, it's working fine. But when I try to get PDF content in controller or save file on server directory then it give me error like

> wkhtmltopdf binary is not found or not executable: /usr/bin/wkhtmltopdf

For rest of the engines I can get PDF stream and also can save on server dir. But I would like to use "WkHtmlToPdf" engine. Anyone with any idea?

My Code:
```
$CakePdf = new CakePdf();
$CakePdf->template('/SendPdf/pdf/email_pdf', 'default');
$CakePdf->viewVars(compact('company_details'));
$CakePdf->write(UPLOADS_PROFILE_IMAGES.'test.pdf', true);
```
