### ISSUE TITLE
possible options in CakePdf.php missing 'footer' and 'header'

### ISSUE THREAD

**Issue by MathRat** [FriendsOfCake/CakePdf#191]
Hi,

i tried for many hours to add a footer to my WKhtmltopdf generated pdf document. At last, i add 'footer' to options array in __construct-Method in CakePdf.php and this works for me.

Why are this two options for header and footer missed here? Is there a better method to add a footer in my documents?

**Comment by steffex** [comment]
There are more options missing from the list. I would like to have the option to set the page-height and page-width.

**Comment by ADmad** [comment]
Patches are welcome to add missing features.

**Comment by ADmad** [comment]
You can use the `options` key in config to pass any additional options you want as shown in readme example.
