### ISSUE TITLE
Add support for wkhtmltopdf's '--replace' argument which takes two parameters

### ISSUE THREAD

**Issue by p-try** [FriendsOfCake/CakePdf#196]
Currently, the ['--replace' argument](http://wkhtmltopdf.org/usage/wkhtmltopdf.txt) for wkhtmltopdf is not useable in CakePdf.engine.options because it takes two parameters. See Line 122 of WkHtmlToPdfEngine.php.

**Comment by ADmad** [comment]
A patch for suggested enhancement is welcome.

**Comment by p-try** [comment]
Here you go: #197 
Usage would be like:
```
Configure::write('CakePdf.engine.options', [
	'replace' => [
		'textToReplace1' => 'replacement1',
		'textToReplace2' => 'replacement2'
	]
]);
```
