### ISSUE TITLE
no font rendered

### ISSUE THREAD

**Issue by maikusch** [FriendsOfCake/CakePdf#200]
hey, i use wkhtmltopdf with cakePdf
i added a @font-face, but the pdf is completely without font. only white pages came out.
here my @font-face:

`@font-face {
 font-family: "Arial";
 src: url(data:font/truetype;charset=utf-8;base64,...) format("truetype");
font-weight: normal;
font-style: normal;`

and then i use

`*, body {
font-family: "Arial", sans-serif;
}`

but no one letter is to see in this pdf.
If i do that without this font-face all is fine.
but the font is not fine, because i need this.
wkhtmltopdf: 0.12.0 and 0.12.2.1 (with patched qt)

**Comment by ADmad** [comment]
Sorry but we cannot offer help for specific rendering issues. Please post your issue on a more appropriate help forum for the rendering engine.
