### ISSUE TITLE
Can not capture proper image from webpage in PDF with CakePdf Plugin.

### ISSUE THREAD

**Issue by Kkukadiya** [FriendsOfCake/CakePdf#205]
I have used this plugin to generate the pdf file of my view page. Everything working is fine. But one problem is that I have an image on my view page. When creating pdf file from the view page the image which is in my view page is not displayed properly in my pdf file generated from view page. Only some portion of the image is displayed in pdf file. 

Any solutions for this problem are appreciated.

**Comment by ADmad** [comment]
Sorry but I can't provide any assistance for specific rendering issues.
