### ISSUE TITLE
loadComponent

### ISSUE THREAD

**Issue by tgoeminne** [FriendsOfCake/CakePdf#206]
I am using this plugin but it seems to not use the components and settings loaded in the appcontroller.

I need to make another initialize in the controller and copy contents of appcontroller, then it works.

Can tell me why this happen?

**Comment by Spriz** [comment]
@tgoeminne did you manage to fix this? Can you gist some reproducing code? Or even better upload a minimum working example to github? If i understand your problem correctly we have the same setup working with controllers inheriting from an `AppController` which has the setup of `CakePDF`.

**Comment by josegonzalez** [comment]
Components aren't used within templates, and this plugin works at the view layer, so in all likelihood you probably overrode your `Controller::initialize()` or `Controller::beforeFilter()` methods without calling the parent method.
