### ISSUE TITLE
Split up combined get/set methods to follow Cake conventions

### ISSUE THREAD

**Issue by Spriz** [FriendsOfCake/CakePdf#208]
What's the opinion on this?

Immutability seems like a 👍  to me - and better follow same convention across projects? Is it worth the BC break on a stable plugin like CakePDF?

**Comment by ADmad** [comment]
> Is it worth the BC break on a stable plugin like CakePDF?

I think not :)

**Comment by dereuromark** [comment]
Yes ist is, Version Numbers are cheap.
 especially if you can make it BC, with only deprecations for old methods :)

**Comment by Spriz** [comment]
True, we can go with deprecations. 👍

**Comment by ADmad** [comment]
With deprecations sounds fine.

**Comment by ADmad** [comment]
Doesn't seem like anyone is interested in making a PR for this hence closing. We would be happy to accept a PR for it in future.
