### ISSUE TITLE
possible FPDI enhancement

### ISSUE THREAD

**Issue by swaygr** [FriendsOfCake/CakePdf#21]
I have a project I'm working on and would like to use an existing PDF as a template to write on. I have come across a way to use FPDI with TCPDF to combine the HTML-to-PDF rendering of TCPDF with the template support of FPDI. I thought it would be neat to have FPDI included in this plugin and have a settings option when you define CakePdf config that points to a template PDF to use.

Just a thought.

Reference: http://www.setasign.de/products/pdf-php-solutions/fpdi/demos/tcpdf-demo/

**Comment by dakota** [comment]
No pull request materialised for this. If you'd like to incorporate FPDI we would welcome a PR!
