### ISSUE TITLE
wkhtmltopdf binary is not found or not executable (on linux)

### ISSUE THREAD

**Issue by pogs94** [FriendsOfCake/CakePdf#210]
Hello guys, 

I was developing in my local computer (Windows 7), and the plugin was working fine.

But now, i'm trying to host it on a linux computer, and i receive the following message ..

![capturar3](https://cloud.githubusercontent.com/assets/17783686/26280534/d238843c-3dae-11e7-930a-015671fbc430.JPG)

I believe that the path is correct. (commented line i was using on Windows, and it was working fine!)

![capturar](https://cloud.githubusercontent.com/assets/17783686/26280538/e85c9618-3dae-11e7-937c-3c94f952ad8d.JPG)

My FTP Print

![capturar2](https://cloud.githubusercontent.com/assets/17783686/26280540/f671e078-3dae-11e7-8812-a23895bc856b.JPG)

Thanks for any tips.

**Comment by rafaelios** [comment]
You need to give execute permission.

**Comment by josegonzalez** [comment]
What @rafaelios said.
