### ISSUE TITLE
Invalid stream reference provided if uploaded file is in the server request

### ISSUE THREAD

**Issue by Manuel1948** [FriendsOfCake/CakePdf#211]
This are the vendor stack frame -, this happens when I have an uploaded file in my server request and wanted to use the CakePdf->write/output function. Why is this happening or what can I do else than redesign my way to deliver my pdf.

/[...fullpath...]/vendor/friendsofcake/cakepdf/src/Pdf/CakePdf.php toggle arguments
    protected function _render()
    {
        $viewClass = $this->viewRender();
        $viewClass = App::className($viewClass, 'View', $viewClass == 'View' ? '' : 'View');
        $View = new $viewClass(Request::createFromGlobals());
        $View->viewVars = $this->_viewVars;
        $View->theme = $this->_theme;
        $View->layoutPath = $this->_layoutPath;
        $View->templatePath = $this->_templatePath;

( ! ) Xdebug: user triggered in /[...fullpath...]/src/Template/Error/error500.ctp on line 33
Call Stack
#	Time	Memory	Function	Location
1	0.0001	364616	{main}( )	.../index.php:0
2	0.0013	556568	Cake\Http\Server->run( )	.../index.php:37
3	0.0069	1229600	Cake\Http\Runner->run( )	.../Server.php:80
4	0.0069	1229600	Cake\Http\Runner->__invoke( )	.../Runner.php:51
5	0.0069	1229976	DebugKit\Middleware\DebugKitMiddleware->__invoke( )	.../Runner.php:65
6	0.0095	1462000	Cake\Http\Runner->__invoke( )	.../DebugKitMiddleware.php:52
7	0.0097	1463688	Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke( )	.../Runner.php:65
8	0.0175	1851520	Cake\Error\Middleware\ErrorHandlerMiddleware->handleException( )	.../ErrorHandlerMiddleware.php:94
9	0.0191	1876304	Cake\Error\ExceptionRenderer->render( )	.../ErrorHandlerMiddleware.php:110
10	0.0196	1896032	Cake\Error\ExceptionRenderer->_outputMessage( )	.../ExceptionRenderer.php:200
11	0.0206	1931792	Cake\Error\ExceptionRenderer->_outputMessage( )	.../ExceptionRenderer.php:334
12	0.0206	1931792	Cake\Controller\Controller->render( )	.../ExceptionRenderer.php:325
13	0.0210	1933952	Cake\View\View->render( )	.../Controller.php:623
14	0.0212	1934992	Cake\View\View->_render( )	.../View.php:596
15	0.0213	1935480	Cake\View\View->_evaluate( )	.../View.php:972
16	0.0214	1952512	include( '/[...fullpath...]/src/Template/Error/error500.ctp' )	.../View.php:1011
17	0.0217	1970264	xdebug_print_function_stack ( )	.../error500.ctp:33
If you want to customize this error message, create src/Template/Error/error500.ctp

toggle vendor stack frames
⟩ Zend\Diactoros\Stream->setStream
ROOT/vendor/zendframework/zend-diactoros/src/Stream.php, line 38
⟩ Zend\Diactoros\Stream->__construct
ROOT/vendor/zendframework/zend-diactoros/src/UploadedFile.php, line 128
⟩ Zend\Diactoros\UploadedFile->getStream
CORE/src/Http/ServerRequest.php, line 436
⟩ Cake\Http\ServerRequest->_processFiles
CORE/src/Http/ServerRequest.php, line 337
⟩ Cake\Http\ServerRequest->_setConfig
CORE/src/Http/ServerRequest.php, line 276
⟩ Cake\Http\ServerRequest->__construct
CORE/src/Http/ServerRequestFactory.php, line 57
⟩ Cake\Http\ServerRequestFactory::fromGlobals
CORE/src/Http/ServerRequest.php, line 231
⟩ Cake\Http\ServerRequest::createFromGlobals
ROOT/vendor/friendsofcake/cakepdf/src/Pdf/CakePdf.php, line 939
⟩ CakePdf\Pdf\CakePdf->_render
ROOT/vendor/friendsofcake/cakepdf/src/Pdf/CakePdf.php, line 285
⟩ CakePdf\Pdf\CakePdf->output
ROOT/vendor/friendsofcake/cakepdf/src/Pdf/CakePdf.php, line 337
⟩ CakePdf\Pdf\CakePdf->write
APP/Controller/StickersController.php, line 141
⟩ App\Controller\StickersController->index
CORE/src/Controller/Controller.php, line 440
⟩ Cake\Controller\Controller->invokeAction
CORE/src/Http/ActionDispatcher.php, line 119
⟩ Cake\Http\ActionDispatcher->_invoke
CORE/src/Http/ActionDispatcher.php, line 93
⟩ Cake\Http\ActionDispatcher->dispatch
CORE/src/Http/BaseApplication.php, line 78
⟩ Cake\Http\BaseApplication->__invoke
CORE/src/Http/Runner.php, line 65
⟩ Cake\Http\Runner->__invoke
CORE/src/Routing/Middleware/RoutingMiddleware.php, line 59
⟩ Cake\Routing\Middleware\RoutingMiddleware->__invoke
CORE/src/Http/Runner.php, line 65
⟩ Cake\Http\Runner->__invoke
CORE/src/Routing/Middleware/AssetMiddleware.php, line 88
⟩ Cake\Routing\Middleware\AssetMiddleware->__invoke
CORE/src/Http/Runner.php, line 65
⟩ Cake\Http\Runner->__invoke
CORE/src/Error/Middleware/ErrorHandlerMiddleware.php, line 92
⟩ Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke
CORE/src/Http/Runner.php, line 65
⟩ Cake\Http\Runner->__invoke
ROOT/vendor/cakephp/debug_kit/src/Middleware/DebugKitMiddleware.php, line 52
⟩ DebugKit\Middleware\DebugKitMiddleware->__invoke
CORE/src/Http/Runner.php, line 65
⟩ Cake\Http\Runner->__invoke
CORE/src/Http/Runner.php, line 51
⟩ Cake\Http\Runner->run
CORE/src/Http/Server.php, line 80
⟩ Cake\Http\Server->run
ROOT/webroot/index.php, line 37

**Comment by johnywind** [comment]
the only solution I found so far is disabling output_buffering in php.ini:
output_buffering = Off
