### ISSUE TITLE
wkhtmltopdf not supporting config option 'binary'

### ISSUE THREAD

**Issue by yild** [FriendsOfCake/CakePdf#213]
My system is debian64, I was trying to use wkhtmltopdf with my cakephp app but without a success.

https://github.com/FriendsOfCake/CakePdf/issues/27#issuecomment-62849245
this post give me some pointers, I've created additional bash script as described and was going to set 'binary' config option but it apparently is ignored by WkHtmlToPdfEngine.

ATM I had to directly modify WkHtmlToPdfEngine $_binary field in vendor\friendsofcake\cakepdf\src\Pdf\Engine\WkHtmlToPdfEngine.php.

**Comment by ADmad** [comment]
How exactly did you try to set the `binary` config?

**Comment by yild** [comment]
Good` question...

at first I've used code described in above comment

Configure::write('CakePdf', [
    'binary' => '/usr/local/bin/wkhtmltopdf', 
    'engine' => 'CakePdf.WkHtmlToPdf',
    'margin' => [
        'bottom' => 20,
        'left' => 20,
        'right' => 20,
        'top' => 20
    ],
    'orientation' => 'portrait',
    'download' => true
]);

but after your question I've dig deeper into your examples and modified code as described in Configuration at https://github.com/FriendsOfCake/CakePdf and it works!

Configure::write('CakePdf', [
    'binary' => '/usr/local/bin/wkhtmltopdf', 
    'engine' => [
		'className' => 'CakePdf.WkHtmlToPdf',
		'binary' => './usr/local/bin/wkhtmltopdf'
	],
    'margin' => [
        'bottom' => 20,
        'left' => 20,
        'right' => 20,
        'top' => 20
    ],
    'orientation' => 'portrait',
    'download' => true
]);

Sorry my mistake :(
