### ISSUE TITLE
Render multiple pages of pdf

### ISSUE THREAD

**Issue by afandiyusuf** [FriendsOfCake/CakePdf#216]
hello, any documentation about how to render multiple pages of pdf?,
I knew that cakepdf will render multiple pages of pdf automatically,
But i need control of every page.
like this.

- page1

this is litle content of page 1

- end of page1

- page2

just a blank page

- end of page2

Sory for my english.

**Comment by ADmad** [comment]
Use the  "page-break-before" and "page-break-after" CSS attributes. Goggle for more info.

**Comment by waspinator** [comment]
make sure that your div is not absolute and that `float: none`
