### ISSUE TITLE
CAKEPDF/wkhtmltopd  downloads a text file instead a PDF file

### ISSUE THREAD

**Issue by parsifalzgz** [FriendsOfCake/CakePdf#217]
CAKEPDF/wkhtmltopd  downloads a text file instead a PDF file.
In CakePHP 3.0 , using the PLUGIN CAKEPDF

**my bootstrap.php:

```
Plugin::load('CakePdf', array('bootstrap' => true, 'routes' => true));
 
Plugin::load('CakePdf', array('bootstrap' => true, 'routes' => true));
Configure::write('CakePdf', [
'engine' => [
        'className' => 'CakePdf.WkHtmlToPdf',
        'binary' => 'C:\\Progra~1\\wkhtmltopdf\\bin\\wkhtmltopdf.exe',						
        'options' => [
            'print-media-type' => false,
            'outline' => true,
            'dpi' => 96
        ],
    ],
    'download' => true
]);
```

**my routes.php: .......

```
```
Router::scope('/users/view', function ($routes) {
    $routes->extensions('pdf');
    $routes->connect('/view/*', ['controller' => 'Users', 'action' => 'view']);
    $routes->fallbacks('InflectedRoute');
});
```

Router::scope('/', function ($routes) {

......
```

USERS CONTROLLER:

```
class UsersController extends AppController
{
 public function initialize()
    {
        parent::initialize();
        $this->loadComponent('RequestHandler');
    } 
    public function view($id = null)
    {
        $user = $this->Users->get($id, [
            'contain' => []
        ]);
        $this->viewBuilder()->options([
            'pdfConfig' => [
                'orientation' => 'portrait',
                'filename' => 'User_' . $id . '.pdf'
            ]
        ]);
        $this->set('user', $user);		
    }
```

Everything is Ok, BUT when i click in my browser this:

/cakephp/users/view/5.pdf

The file should be  'User_15.pdf' but is '15.pdf, so maybe this code is not working:            UsersController:View(): $this->viewBuilder()->options([  'pdfConfig' => [ 'orientation' => 'portrait', 'filename' =>  'User_' . $id . '.pdf' ] ]);

 
About the MimeTypes,  i look at the debug history and says "**GET 200 application/pdf      /fct/users/view/13.pdf** " it seems to be OK!! but not working..

 

the links looks right (in the  cakephp debug appears 200 mimetype: Application/pdf).  <?=  $this->Html->link(__('Export1 to PDF'), ['action' => 'view',  $user->id, '_ext' => 'pdf', '?' => array('download' => 1)  ]); ?>

The file should be 'User_15.pdf' but is '15.pdf, so maybe this code is not working:UsersController:View(): $this->viewBuilder()->options([ 'pdfConfig' => [ 'orientation' => 'portrait', 'filename' => 'User_' . $id . '.pdf' ] ]); 

Reinstall the plugin with Composer,even the version of Xamp 3.2.2 (it doesnt still working!

 I dont get a proper PDF file, instead of that i download a text file like this (the view ctp seems to work)...any IDEA??? :

```
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>    <title>
        Users\pdf    </title>
    <link rel="stylesheet" href="http://localhost/fct/css/style.css"/></head>
<body>
    <div id="container">
        <div id="content">
            <div class="users view">
<h2>User</h2>
    <dl>
        <dt>Id</dt>
        <dd>
            15            &nbsp;
        </dd>

        <dt>Created</dt>
        <dd>
            8/19/16, 11:14 PM            &nbsp;
        </dd>
        <dt>Modified</dt>
        <dd>
            8/19/16, 11:14 PM            &nbsp;
        </dd>
    </dl>
</div>        </div>
    </div>
</body>
</html>

```

**Comment by ADmad** [comment]
Sorry but we cannot provide support for configuration/setup issues with individual engine. Please use one of Cake's official help forums for help.
