### ISSUE TITLE
How to set footer in cakepdf using mpdf engine

### ISSUE THREAD

**Issue by shradha1992** [FriendsOfCake/CakePdf#219]
I would like to add footer paging number to my pdf. Code below:

Configure::write('CakePdf', [
                'engine' => 'CakePdf.Mpdf',
                //'pageSize'=>'Letter',
                'orientation' => 'landscape', //potrait
                'download' => true
                ]);
            $CakePdf = new \CakePdf\Pdf\CakePdf();
            $CakePdf->template('newsletter', 'default');
            $CakePdf->viewVars(array('data'=>$property_data,'vendor'=>$this->request->data('veendor_id')));
            $pdf = $CakePdf->Output();

**Comment by ADmad** [comment]
This is not a help forum. The issue tracker is reserved for possible
bugs and feature enhancements to the CakePdf plugin.
Please visit one of the following CakePHP support forums for help:

* [CakePHP Official Forum](http://discourse.cakephp.org)
* [Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
* [Slack channel](http://cakesf.herokuapp.com/)
* #cakephp channel on irc.freenode.net

Thanks!
