### ISSUE TITLE
CakePDF not rendering 

### ISSUE THREAD

**Issue by mojeedoyedeji** [FriendsOfCake/CakePdf#220]
CakePDF not rendering with DomPDF or Wkhtmltopdf but works with Tcpdf. Page Keeps loading on end. No errors in error.log Just a loading page without end..

**Comment by Spriz** [comment]
This sure sounds like a problem with your DomPDF and Wkhtmltopdf rather than with CakePdf - what did you try until now, what did you expect and what happened?

**Comment by Turpoint** [comment]
Was there a solution? I have the same problem using DomPdf and Mpdf. Tcpdf. It used to work when I was using a MAMP stack. But now I use the `bin/cake server` command, and the page just keeps loading (PdfView).
