### ISSUE TITLE
mPDF 7.0 support?

### ISSUE THREAD

**Issue by squalltua** [FriendsOfCake/CakePdf#221]
CakePdf not support mPDF 7.0

**Comment by ewbarnard** [comment]
In case anyone else runs across this... to get the current plugin (3.2.3) working with mpdf, I require mpdf/mpdf 6.1.* and save/restore the debug flag:

```
$debug = Configure::read('debug');
Configure::write('debug', 0);
/* use CakePdf */
Configure::write('debug', $debug);
```
