### ISSUE TITLE
Render PDF without pdf extension

### ISSUE THREAD

**Issue by Xoto1162** [FriendsOfCake/CakePdf#226]
Hello, I need to render a pdf without the pdf extension. The documentation said "send a Accept: application/pdf header instead." so in my view method I have this but is not work

```php
public function view($id = null)
    {
        $devis = $this->Devis->get($id, [
            'contain' => ['Users', 'ArticlesDevis']
        ]);

        $this->set('devi', $devis);
        $this->response->withHeader('Accept', 'application/pdf');
    }
```

**Comment by ADmad** [comment]
`Accept` is a request header not response header.

**Comment by Xoto1162** [comment]
@ADmad 
Same problem, I have test in my controller with this line but not work
```pdf
$this->request->withHeader('Accept', 'application/pdf');
```
