### ISSUE TITLE
Problem with pdf subfolder / missing template

### ISSUE THREAD

**Issue by Shubaarb** [FriendsOfCake/CakePdf#236]
I follwed every installation and configuration  step described in the guide, and i'm trying to render the pdf and force download. 
As the guide says, the template should be placed in a "pdf" subfolder like "invoice/pdf/view.ctp" to trigger the pdf rendering (if I have understood), and I can't figure how Cake could ever find a view template in a subfolder. 
Cake actually shows a missing template exception doing this. 
I'm stuck here!

**Comment by pieroGit** [comment]
hi, probably you have missed some configuration

**Comment by Shubaarb** [comment]
I installed  cakepdf with  composer require command

That's my configuration in bootstrap.php
Plugin::load('CakePdf', ['bootstrap' => true, 'routes' => true]);

```
Plugin::load('CakePdf', ['bootstrap' => true, 'routes' => true]);

Configure::write('CakePdf', [
		'engine' => 'CakePdf.WkHtmlToPdf',
        'margin' => [
            'bottom' => 30,
            'left' => 20,
            'right' => 20,
            'top' => 30
        ],
        'orientation' => 'portrait',
        'download' => true,
    //    'encoding' => 'UTF-8'
    ]);
```
In routes.php i added Router::extensions(['pdf']); before Router::scope('/', function (RouteBuilder $routes) {...

And here's my controller action:


```
public function savepdf($id_paz){   
		$anamnesi = $this->AnamnesiPazienti->find()->where(['pazienti_id' => $id_paz]);
		$this->loadModel('Pazienti');
		$paziente = $this->Pazienti->get($id_paz);	
		$this->viewBuilder()->options([
				'pdfConfig' => [
						'filename' => 'Anam_paz-' . $id_paz . '.pdf'
				]
		]); 
		$this->set('paziente', $paziente);
		$this->set('anamnesi', $anamnesi);
		$this->set('modelPazienti', $this->Pazienti);

	}
```

**Comment by pieroGit** [comment]
configuration seems to be correct!
Your url is link application/controller/savepdf/1.pdf ?

**Comment by Shubaarb** [comment]
Yes, that's the link  format that i call.
Is cakepdf itself supposed to recognize that subfolder and let the app find the template?

**Comment by pieroGit** [comment]
Cakepdf check for subfolder pdf in template directory.
For example Controller: ReportController | Action : pdf -> Template/Report/pdf/pdf.ctp

**Comment by Shubaarb** [comment]
So that appears not to be working, I can't imagine what else could be wrong!

**Comment by pieroGit** [comment]
in your action add the following code:

 Configure::write('CakePdf.download', true);

**Comment by Shubaarb** [comment]
Not working... and that's already  in bootstrap.php

**Comment by pieroGit** [comment]
hi, can you post your routes.php? or you can upload your app in some repositories?

**Comment by Shubaarb** [comment]
This is my routes.php
I prefer to post single portions of code, if you want to see more tell me.
Thank you
```
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass(DashedRoute::class);


Router::extensions(['pdf']);

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
    
});

/**
 * Load all plugin routes. See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

```

**Comment by pieroGit** [comment]
you can try to add a custom route in you routes.php like

Router::scope('/invoice/:id', function (RouteBuilder $routes) {
    $routes->addExtensions(['pdf']);
    $routes->connect('/', ['controller' => 'Invoice', 'action' => 'pdf'],
        ['id' => '\d+', 'pass' => ['id']]);

});

just before Router::extensions(['pdf']);

you can test this action by app/invoice/id.pdf

**Comment by Shubaarb** [comment]
I added this but nothing changed, the route is correctly set, it browses the correct action but still doesn't find the view within the subfolder
```
Router::scope('/anamnesi-pazienti/:id', function (RouteBuilder $routes) {
    $routes->addExtensions(['pdf']);
    $routes->connect('/', ['controller' => 'anamnesi-pazienti', 'action' => 'savepdf'],
    ['id' => '\d+', 'pass' => ['id']]);

});
```

**Comment by pieroGit** [comment]
Did you have used following code in your controller?

public function initialize()
    {
        parent::initialize();
        $this->loadComponent('RequestHandler');
    }

**Comment by Shubaarb** [comment]
I placed `$this->loadComponent('RequestHandler');` in the AppController, so it should be inherited, right?

**Comment by pieroGit** [comment]
no,you must place that code in your controller that extend appcontroller

**Comment by Shubaarb** [comment]
I added this to my controller but nothing changed, i'm pretty sure it's the same thing of placing it in AppController initialize method, that is called by parent::initialize();
```
public function initialize()
	{
		parent::initialize();
		
		$this->loadComponent('RequestHandler');
	}
```

**Comment by pieroGit** [comment]
it's same thing but you need to call the parent::initialize method

**Comment by Shubaarb** [comment]
However I tried   placing it in my custom controller too and nothing changed

**Comment by ADmad** [comment]
Your routes setup is not proper. You are supposed to use CamelCased class name for `'controller'` key and the template folder should also have same name.

```
Router::scope('/anamnesi-pazienti/:id', function (RouteBuilder $routes) {
    $routes->addExtensions(['pdf']);
    $routes->connect('/', ['controller' => 'anamnesi-pazienti', 'action' => 'savepdf'],
    ['id' => '\d+', 'pass' => ['id']]);

});
```

Closing as the plugin works as documented. Use one of the official cake forums for support.
