### ISSUE TITLE
Problems using built-in server

### ISSUE THREAD

**Issue by Turpoint** [FriendsOfCake/CakePdf#244]
I used to develop on a MAMP-stack, where DomPdf used to work. Now I started using the built-in `bin/cake server`, but the pdf view keeps loading. The same happens using Mpdf.

**Comment by ADmad** [comment]
A fix is welcome if you can figure out what's causing the problem when using PHP's internal server.

Try explicitly setting `App.baseUrl` and generating full URLs for assets in the PDF template.

**Comment by Turpoint** [comment]
Thanks! That worked :) 
Setting `'fullBaseUrl' => true,` in app.config fixed it.
