### ISSUE TITLE
LoadModel error when displaying Cell in PDFView

### ISSUE THREAD

**Issue by Fluit** [FriendsOfCake/CakePdf#247]
I insert a Cell in a view which is rendered in PDF like this: 
`$this->cell('idvs::display_opmerkingen_idv',[$result->id])`
In IdvsCell, the function display_opmerkingen_idv needs to load IdvsModel.

When loading the PDF I get the error: 
> Call to undefined method CakePdf\View\PdfView::loadModel()

> 

( ! ) Xdebug: user triggered in C:\xampp\htdocs\myKMG_32\src\Template\Error\error500.ctp on line 27
--

1 | 0.2050 | 139528 | {main}( ) | ...\index.php:0
2 | 0.4550 | 4575224 | Cake\Routing\Dispatcher->dispatch( ) | ...\index.php:37
3 | 0.4600 | 4618280 | Cake\Http\ActionDispatcher->dispatch( ) | ...\Dispatcher.php:60
4 | 0.5650 | 6034920 | Cake\Http\ActionDispatcher->_invoke( ) | ...\ActionDispatcher.php:93
5 | 1.1625 | 10030488 | Cake\Controller\Controller->render( ) | ...\ActionDispatcher.php:125
6 | 1.1900 | 10725624 | CakePdf\View\PdfView->render( ) | ...\Controller.php:623
7 | 1.1900 | 10725832 | Cake\View\View->render( ) | ...\PdfView.php:105
8 | 1.2500 | 11042928 | Cake\View\View->_render( ) | ...\View.php:610
9 | 1.2525 | 11043640 | Cake\View\View->_evaluate( ) | ...\View.php:986
10 | 1.2525 | 11128192 | include( '...\src\Template\Idvs\pdf\doc.ctp' ) | ...\View.php:1025
11 | 1.2575 | 11133208 | App\View\Cell\IdvsCell->display_opmerkingen_idv( ) | ...\doc.ctp:212
12 | 1.2600 | 11133344 | Cake\Error\BaseErrorHandler->Cake\Error\{closure}( ) | ...\BaseErrorHandler.php:0
13 | 1.2600 | 11134512 | Cake\Error\BaseErrorHandler->handleFatalError( ) | ...\BaseErrorHandler.php:105
14 | 1.2925 | 11563096 | Cake\Error\BaseErrorHandler->handleException( ) | ...\BaseErrorHandler.php:225
15 | 1.2925 | 11563200 | Cake\Error\ErrorHandler->_displayException( ) | ...\BaseErrorHandler.php:187
16 | 1.3075 | 11669360 | Cake\Error\ExceptionRenderer->render( ) | ...\ErrorHandler.php:137
17 | 1.3100 | 11673688 | Cake\Error\ExceptionRenderer->_outputMessage( ) | ...\ExceptionRenderer.php:200
18 | 1.3200 | 11707512 | Cake\Error\ExceptionRenderer->_outputMessage( ) | ...\ExceptionRenderer.php:334
19 | 1.3300 | 11736080 | Cake\Error\ExceptionRenderer->_outputMessageSafe( ) | ...\ExceptionRenderer.php:331
20 | 1.3550 | 12228232 | Cake\View\View->render( ) | ...\ExceptionRenderer.php:364
21 | 1.3575 | 12229928 | Cake\View\View->_render( ) | ...\View.php:610
22 | 1.3600 | 12230520 | Cake\View\View->_evaluate( ) | ...\View.php:986
23 | 1.3600 | 12255680 | include( 'C:\xampp\htdocs\myKMG_32\src\Template\Error\error500.ctp' ) | ...\View.php:1025
24 | 1.3625 | 12274352 | xdebug_print_function_stack ( ) | ...\error500.ctp:27

Thanx for helping me out.

**Comment by ADmad** [comment]
This is not a help forum. The issue tracker is reserved for possible
bugs and feature enhancements to the CakePdf plugin.
Please visit one of the following CakePHP support forums for help:

* [CakePHP Official Forum](http://discourse.cakephp.org)
* [Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
* [Slack channel](http://cakesf.herokuapp.com/)
* #cakephp channel on irc.freenode.net

Thanks!
