### ISSUE TITLE
Class 'Dompdf\Dompdf' not found

### ISSUE THREAD

**Issue by upworkmkd** [FriendsOfCake/CakePdf#260]
I am getting this error .
Can you please help me for this ?

Error in: ROOT\vendor\friendsofcake\cakepdf\src\Pdf\Engine\DomPdfEngine.php, line 37
If you want to customize this error message, create src\Template\Error\error500.ctp

**Comment by ADmad** [comment]
You need to install dompdf as stated in readme.
