### ISSUE TITLE
How can i force download the pdf

### ISSUE THREAD

**Issue by fullstackdevloper** [FriendsOfCake/CakePdf#261]
Hey is there a way so that i can force download this as pdf ?
public function downloadStatement() {
        $this->autoRender = false;
        $this->loadModel('Statements');
        $CakePdf = new \CakePdf\Pdf\CakePdf();
        $CakePdf->template('agencystatement', 'default');
        $CakePdf->viewVars($this->viewVars);
        $pdf = $CakePdf->output();
    }

**Comment by ADmad** [comment]
This is not a help forum. The issue tracker is reserved for possible
bugs and feature enhancements to the CakePdf plugin.
Please visit one of the following CakePHP support forums for help:

* [CakePHP Official Forum](http://discourse.cakephp.org)
* [Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
* [Slack channel](http://cakesf.herokuapp.com/)
* #cakephp channel on irc.freenode.net

Thanks!
