### ISSUE TITLE
Usage with phpwkhtmltopdf

### ISSUE THREAD

**Issue by BenoKop** [FriendsOfCake/CakePdf#262]
Hello all,

I just downloaded the following component with composer:
https://github.com/mikehaertl/phpwkhtmltopdf

Is it possible tu use CakePdf with this instead of getting the binary of wkhtmltopdf ?

Thanks in advance.

**Comment by ADmad** [comment]
No it's not. `phpwkhtmltopdf` is also just a wrapper for the wkhtmltopdf binary.
