### ISSUE TITLE
filename option ignored ?

### ISSUE THREAD

**Issue by BenoKop** [FriendsOfCake/CakePdf#263]
Hello,

I just installed CakePdf, i can generate the wanted PDF but the name is always the ID set on the URL:

I put Router::extensions(['pdf']); before the standard Router::scope in routes.php

global config in my controller:
```
// Configuration PDF
Configure::write('CakePdf', [
    'engine' => 'CakePdf.DomPdf',
    'orientation' => 'portrait',
    // 'download' => true,
]);
```

In the controller method:
```
$filename = __('Compte rendu') . '-' . $meeting->title . '.pdf';
        $this->viewBuilder()->options([
            'pdfConfig' => [
                'filename' => $filename,
            ]
        ]);
$this->set(compact('meeting'));
```

When i access to /meetings/pdf-statements/1.pdf, the name of the pdf is still 1.pdf.
The user needs to rename the pdf after the download.

Did i miss something ?

**Comment by ADmad** [comment]
Duplicate #254.

**Comment by ADmad** [comment]
You need to add `'download' => true` also to your view builder options.

**Comment by BenoKop** [comment]
I don't want to force the download, I want to open it in the Browser viewer before.

**Comment by ADmad** [comment]
Then setup routing to get the filename you want. Unless you force download you can't have a filename different than URL. That's just how HTTP works.
