### ISSUE TITLE
Use this with cakePHP 3.2

### ISSUE THREAD

**Issue by nakoda** [FriendsOfCake/CakePdf#265]
Hello,

I have a application built with cakephp 3.2, how i can use this plugin with this application.

I used it with other application built with 3.5 and working grrat and i like it

Please help me to setup this with 3.2

**Comment by ADmad** [comment]
This is not a help forum. The issue tracker is reserved for possible
bugs and feature enhancements to the CakePdf plugin.
Please visit one of the following CakePHP support forums for help:

* [CakePHP Official Forum](http://discourse.cakephp.org)
* [Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
* [Slack channel](http://cakesf.herokuapp.com/)
* #cakephp channel on irc.freenode.net

Thanks!
