### ISSUE TITLE
How to Use the latest Cakepdf

### ISSUE THREAD

**Issue by sunilj143** [FriendsOfCake/CakePdf#267]
Can you please give an intruction on How to use the latest CakePdf Plugin with Cakephp 2.x (2.9.3 or 2.10.10)

I have tried with Cakepdf 1.0.1 by second way 'Create PDF for email attachment, file storage etc.' 
 but getting error & attached the screenshot of output of pdf
engine dompdf
![cakepdf](https://user-images.githubusercontent.com/36676835/41284406-d45c97b0-6e56-11e8-8bbd-75559d4540a7.png)

**Comment by ADmad** [comment]
This is not a help forum. The issue tracker is reserved for possible
bugs and feature enhancements to the CakePdf plugin.
Please visit one of the following CakePHP support forums for help:

* [CakePHP Official Forum](http://discourse.cakephp.org)
* [Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
* [Slack channel](http://cakesf.herokuapp.com/)
* #cakephp channel on irc.freenode.net

Thanks!
