### ISSUE TITLE
CakePdf not showing any data any error

### ISSUE THREAD

**Issue by roshanapptec** [FriendsOfCake/CakePdf#270]
I am using CakePdf plugin to create pdf files from Html. I've installed plugin using composer and install it in bootstrap.php. Bootstrap.php

> Plugin::load('CakePdf',['bootstrap' => true]);

`Configure::write('CakePdf', [
    'engine' => 'CakePdf.WkHtmlToPdf',
    'margin' => [
        'bottom' => 15,
        'left' => 50,
        'right' => 30,
        'top' => 45
    ],
    'orientation' => 'landscape',
    'download' => true
]);`
Also extension is loaded in routes.php

Router::extensions('json', 'xml', 'pdf');
RequestHandler is also enabled in AppController and I've also use it in my controller. And I've used one method which I want to convert to pdf. Code in controller.

public function generatePdf() {

    $billNumber = "100004";
    $bill = $this->Bills->find("all")
        ->contain(['Users', 'Customers', 'PaymentGateways'])
        ->where(['bill_number' => $billNumber]);
    $billDetails = $this->Bills->BillDetails->find('all')
        ->where(['bill_id' => $billNumber]);
    $this->set(compact('bill', 'billDetails', 'billNumber'));

    $this->viewBuilder()->options([
        'pdfConfig' => [
            'download' => true,
            'filename' => 'Invoice.pdf'
        ]
    ]);

}
And also view is created where output is rendered. generate_pdf.ctp:

<h1></h1>

<p>Banana</p>

<p>Boom !!!</p>
But when I am accessing my method nothing happening in browser. Only my content is showing and no error or warning is showing

**Comment by mohsinrasool** [comment]
I am experiencing the same situation.

**Comment by cnizzardini** [comment]
What version of Cake are you using?

**Comment by mohsinrasool** [comment]
In my case debug info was disabled at multiple places. When I enabled it, some views and templates were missing.

**Comment by ADmad** [comment]
Please use one of Cake's help forums to sort out your issue.
