### ISSUE TITLE
Problems with external CSS

### ISSUE THREAD

**Issue by alexandroldl** [FriendsOfCake/CakePdf#273]
When inserting the CSS Bootstrap file into the Layout file with the statement `<?= $ This->Html->css ('/ vendor/bootstrap/css/bootstrap.min.css', [' fullBase '=> true])?>` I have returned the error" WKHTMLTOPDF did not return any data ".

How could you solve this problem?

> wkhtmltopdf 0.12.5 (with patched qt)
> CakePHP 3.5.0
> CakePdf 3.5.1

Thanks guys.

**Comment by sdevore** [comment]
I don't think the vendor directory is viewable from the install of cake and so a full path doesn't find it.  I usually have to copy those files to be inside the webroot directory or build them with sass to the webfoot/css directory.
