### ISSUE TITLE
Custom binary path on WkHtmlToPdf Engine not working

### ISSUE THREAD

**Issue by ToxSox** [FriendsOfCake/CakePdf#274]
I use CakePDF on my CakePHP 3.6. In my bootstrap.php i have added this lines:
`Configure::write('CakePdf', [
    'engine' => 'CakePdf.WkHtmlToPdf',
    'binary' => '/usr/local/bin/wkhtmltopdf',
    'margin' => [
        'bottom' => 15,
        'left' => 50,
        'right' => 30,
        'top' => 45
    ],
    'orientation' => 'landscape',
    'download' => true
]);`

But the binary option has no result. The plugin try to get the default path of the binary.

**Comment by ADmad** [comment]
Read the README properly. The `binary` key should be nested inside `engine` key.

**Comment by ToxSox** [comment]
O yes, thanks.
