### ISSUE TITLE
Header and Footer wktohtmlpdf

### ISSUE THREAD

**Issue by thiagoreri** [FriendsOfCake/CakePdf#277]
How to create header and footer dinamically?

**Comment by Modicrumb** [comment]
Basically you are not supposed to be asking this here but look at wkhtmltopdf options type wkhtmltopdf -H and you'll figure it out. You'll have to pass in header-html and footer-html options (both which can be cake views). Good luck.

**Comment by ADmad** [comment]
This is not a help forum. The issue tracker is reserved for possible
bugs and feature enhancements to the CakePdf plugin.
Please visit one of the following CakePHP support forums for help:

* [CakePHP Official Forum](http://discourse.cakephp.org)
* [Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
* [Slack channel](http://cakesf.herokuapp.com/)
* #cakephp channel on irc.freenode.net

Thanks!
