### ISSUE TITLE
Image not showing in dompdf

### ISSUE THREAD

**Issue by Shahjalal7311** [FriendsOfCake/CakePdf#279]
Hey There,
I using cakePDF dompdf engine all data is fetching it work well but image is not showing.
I am using absolute url 
<?php echo $this->Html->image('sb_pdf.png', ['alt' => 'CakePHP']); ?>
It show the error `Image not found or unknow type of image`.

What i am wrong?please suggest me.
Thanks

**Comment by ADmad** [comment]
This is not a help forum. The issue tracker is reserved for possible
bugs and feature enhancements to the CakePdf plugin.
Please visit one of the following CakePHP support forums for help:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
#cakephp channel on irc.freenode.net

Thanks!
