### ISSUE TITLE
Suggestion for documentation re: wktohtmlpdf

### ISSUE THREAD

**Issue by sdevore** [FriendsOfCake/CakePdf#282]
So in trying to track down some PDF generation that was very slow  > 30 seconds for a 15 page document on a pretty fast server, doing some research ( starting with https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1510 ) and got a fairly significant performance gain just by setting border-radius to 0px or removing altogether.  For the same PDF went to  < .5 seconds (pdf generation became the fastest part of the generation, the time consuming part shifted to php generating the html to be passed to wktohtmlpdf.

**Comment by ADmad** [comment]
HTML to PDF conversion is tricky business. I am sure each of the engines supported by the plugin have numerous issues/edge cases like this one and at least I don't want to go about documenting them in the plugins' readme.

**Comment by sdevore** [comment]
Feel free to close, I was just amazed at the improvement.
