### ISSUE TITLE
$CakePdf->template(); does not use template file from Plugin

### ISSUE THREAD

**Issue by LDSign** [FriendsOfCake/CakePdf#283]
Hi

The template method only uses template files from the main src folder, but not from a plugin. The viewbuilder gives an error with correct paths (if I delete the main template on leave only the plugin one, which will work on "normal" views):

\app\plugins\Demo\src\Template\Pdf\demo.ctp
\app\src\Template\Pdf\demo.ctp

The plugin one will be fully ignored.

Is this a bug of CakePdf or one of myself?

Thanks,
Frank

**Comment by LDSign** [comment]
Just made one more test. If I set the plugin-name explicitly it will work:

'Demo.demo'

But thats not the way Ive expected it to work.

**Comment by ToX82** [comment]
I was having the same problem. I am using cakepdf in a plugin, and if I do 

`$CakePdf->template('viewinvoice', 'default');`

it doesn't work. If I do this instead

`$CakePdf->template('Myplugin.viewinvoice', 'default');`

it works correctly. I think that this should go into the documentation
