### ISSUE TITLE
Override with viewbuilder()->options engine options

### ISSUE THREAD

**Issue by admindotnu** [FriendsOfCake/CakePdf#286]
Is it possible to change line 65 of PdfView.php
$this->pdfConfig = array_merge(
to
$this->pdfConfig = array_merge_recursive(

`
$this->viewBuilder()->options([
                    'pdfConfig' => [
                        'engine' => [
                            'options' => [
                                'header-left' => 'test']
                        ]]
                ]);
`

If its not changed, it completely overrides the engine array.

Thank you.

**Comment by dereuromark** [comment]
array_merge_recursive() can have other side effects.
Refs also https://github.com/cakephp/cakephp/issues/7267
Maybe you can look into how merging in Cake works using Hash class?

**Comment by ADmad** [comment]
Recursive merge would prevent the ability to unset nested keys. Similar issue has already posted earlier  (I can't find it right now) and closed.
