### ISSUE TITLE
CakePdf configuration ignored by the plugin

### ISSUE THREAD

**Issue by martinurx** [FriendsOfCake/CakePdf#287]
When non-default location for binary is specified, plugin ignores the location and reports not found in the default location.

Configuration:
Configure::write('CakePdf', [
    'binary' => '/usr/local/bin/wkhtmltopdf',
....

Error message:
wkhtmltopdf binary is not found or not executable: /usr/bin/wkhtmltopdf

When the default location is manually changed in the engine file, plugin works.

Using CakePHP 3.7.9

**Comment by ADmad** [comment]
Read the README carefully, the `binary` key needs to be nested inside `engine` key.

**Comment by martinurx** [comment]
Sorry, my bad..
