### ISSUE TITLE
Add debug option for PDF rendering engine - fonts not rendering

### ISSUE THREAD

**Issue by sourjya** [FriendsOfCake/CakePdf#289]
I'm facing issues in rendering PDFs using fonts loaded via the @font-face CSS statement. I don't see any options to enable debug for the rendering engine. Please add some option for the same in future versions.

My engine is DomPDF. 

Thank you.

**Comment by ADmad** [comment]
You can set `CakePdf.engine.options` config to an array and it will be passed to the `Dompdf` constructor.
