### ISSUE TITLE
CakePHP 4.x Compatibility

### ISSUE THREAD

**Issue by kyleweishaupt** [FriendsOfCake/CakePdf#290]
I'm looking to upgrade an application to CakePHP 4.0, but we rely on CakePDF to generate PDFs. 

Composer is throwing the obvious errors that there isn't a compatible release and I noticed the 4.x branch hasn't been touched in a while.

Just wondering if there's anything I can do or if a quick release could be made. 

Thanks for all the hard work! :)

**Comment by dereuromark** [comment]
You can make a PR to finalize the 4.x branch and then someone can release/tag it.

**Comment by gabrielkolbe** [comment]
Has anyone made progress on this? I have manually inserted the cakepdf into the cakephp 4 with a hope that it would work and spend a whole day trying to make sure my configuration is correct and checking through the plugin code to see where the problem lays.. I get 'Failed to load PDF document' it does not give any errors in any debug options. Which makes it difficult , it could be a cake related problem, not referencing the core files, or namespaces or a php 7.2 imcompatibility in the php. Would be great if we can get this to work as I have build a beautiful application in cakephp4 and pdf's is vital for it.

**Comment by dereuromark** [comment]
Make PRs for what doesnt work in https://github.com/FriendsOfCake/CakePdf/tree/cake-4.x
and then ask someone here to start tagging beta versions.
