### ISSUE TITLE
Include CSS Files in Command does not work

### ISSUE THREAD

**Issue by wiifree** [FriendsOfCake/CakePdf#309]
I creating a method in a model class of an table. In this method i create a PDF file like the documentation.
`
$CakePdf = new \CakePdf\Pdf\CakePdf();
$CakePdf->template('invoices_template', 'default');
$CakePdf->viewVars(['invoice' => $invoice]);
// Get the PDF string returned
$CakePdf->write(INVOICES_PATH);
`

 In the template file if the pdf i try to include a separate css file with `echo $this->Html->css('style.css');` 
If i run this method over a web request with the controller method it works fine and all classes are added to the template but if i run the table method over the [command functionality](https://book.cakephp.org/4/en/console-commands.html) the seperate css file does not include. i think this is a bug.

**Comment by ADmad** [comment]
https://github.com/friendsofcake/cakepdf#ensure-css-images-etc-are-loaded-in-pdf

**Comment by wiifree** [comment]
Thanks
Sorry for my mistake. With the command functionality you must include the files over the system paths.
