### ISSUE TITLE
Error in documentation 

### ISSUE THREAD

**Issue by rajithwijepura** [FriendsOfCake/CakePdf#311]
There is an error in documentation

2: Create PDF for email attachment, file storage etc.
You can use CakePdf lib to create raw PDF data with a view template. The view file path would look like `templates/pdf/newsletter.php`. 

Path should be corrected as `templates/Pdf/newsletter.php`.

**Comment by ADmad** [comment]
Which plugin/cakephp version are you using? For CakePHP 4 compatible version the folder is `pdf` as seen in test app here https://github.com/FriendsOfCake/CakePdf/tree/master/tests/test_app/templates/pdf

**Comment by rajithwijepura** [comment]
oh. sorry. I was using older version (3.5)
