### ISSUE TITLE
Using PHP8 impossible with current configuration

### ISSUE THREAD

**Issue by byuilazenbyt** [FriendsOfCake/CakePdf#314]
Right now your composer integration seems to indicate that it isn't going to run on php8

```

  Problem 1
    - aura/intl[3.0.0-beta1, ..., 3.x-dev] require php ^5.6|^7.0 -> your php version (8.0.3) does not satisfy that requirement.
    - friendsofcake/cakephp-csvview 4.0.0 requires cakephp/cakephp ^4.0 -> satisfiable by cakephp/cakephp[4.1.0-beta1, ..., 4.1.7].
    - cakephp/cakephp[4.1.0-beta1, ..., 4.1.7] require aura/intl ^3.0.0 -> satisfiable by aura/intl[3.0.0-beta1, 3.0.0, 3.x-dev].
    - Root composer.json requires friendsofcake/cakephp-csvview 4.0.0 -> satisfiable by friendsofcake/cakephp-csvview[4.0.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

```

This issue tracker is only for reporting bugs (suggesting features) for the plugin itself.

Please **do not** ask support questions for configuring / using a particular engine/library for PDF generation.
Use one of CakePHP's or the particular engine/library's support forum for that.

**Comment by ADmad** [comment]
What's your CakePHP version?

**Comment by byuilazenbyt** [comment]
I was able to install it after looking deeper into the cakephp/cakephp package. I had to do a few things to make a downgrade and drop the cakephp/codesniffer
