### ISSUE TITLE
Custom Engine possible? (Trying weasyprint)

### ISSUE THREAD

**Issue by grosseskino** [FriendsOfCake/CakePdf#316]
Hi!
I'm looking for a PDF Engine that supports CSS-Grid.
Found a supporting engine that runs on python (https://weasyprint.org/)

How could I integrate this for rendering?
I believe it would run through the cli.

**Comment by ADmad** [comment]
Wkhtmltopdf also runs in CLI, so surely you can create your own engine class for other CLI based tools too.

Refer to https://github.com/FriendsOfCake/CakePdf/blob/master/src/Pdf/Engine/WkHtmlToPdfEngine.php.
