### ISSUE TITLE
Problemas ao usar wkhtmltopdf

### ISSUE THREAD

**Issue by StgoDev** [FriendsOfCake/CakePdf#317]
Unfortunately I'm not getting your plugin to run properly, what could you be doing wrong?

![image](https://user-images.githubusercontent.com/33138953/131426337-61ed98e9-3677-4f56-8ada-7cc01bc3a6b1.png)

We've already released the exec and the shell as well.

**Comment by wikosoft** [comment]
Can you paste your pdfConfig? I think your String might be incorrect or something, because I had a similar problem and just tempering with the name fixed my issue. Here's a sample one for the TcPdf engine:
```
$this->viewBuilder()->setOption(
    'pdfConfig',
    [
        'engine' => 'CakePdf.Tcpdf',
        'filename' => 'fileName'
    ]
);
```

**Comment by dakota** [comment]
That means that wkhtmltopdf can't be found. You need to check that the path supplied in config matches exactly to the path that the executable has been placed in

**Comment by ADmad** [comment]
You need to figure out the proper path for the executable and set the `binary` config for the engine.

Closing as there's nothing to do in the plugin code.
