### ISSUE TITLE
Support for CakePHP version 4.3

### ISSUE THREAD

**Issue by viraj-khatavkar** [FriendsOfCake/CakePdf#319]
Hey, the composer file has restricted the dependency to `^4.0` for the cakephp app. However, I want to upgrade my app to `4.3` the latest version of `cakephp/cakephp` - can we please upgrade the `cakephp/cakephp` dependency in this package to `^4.3`? I can send a PR if needed, but just want to confirm if there is anything that I might need to do>

**Comment by ADmad** [comment]
`^4.0` means the plugin can be installed for any `4.x` release of CakePHP.
