### ISSUE TITLE
added support for php extension of wkhtmltox

### ISSUE THREAD

**Issue by mithrandirii** [FriendsOfCake/CakePdf#33]
hi,

we added support to php extension of libwkhtmltox. we extended the WkHtmlToPdfEngine.php. if you want i can send you the file or do an pull request. but i'm new to github and don't know how to do it ;)

to use libwkhtmltox as php extension we used an extended version of php-wkhtmltox from https://github.com/mreiferson/php-wkhtmltox and the current wkhtmltox 0.12 from https://github.com/antialize/wkhtmltopdf (+wkhtmltox-qt from gitorious.org/~antialize/qt/antializes-qt). we had to extend the php module with string input/output and error reporting. we added an issue/pull request there also.

greetings from germany

dominik

**Comment by dakota** [comment]
No updates on this, and the project seems to be dormant.
