### ISSUE TITLE
Can't get orientation to work with Mpdf

### ISSUE THREAD

**Issue by connelhooley** [FriendsOfCake/CakePdf#38]
This is in my bootstrap

CakePlugin::load('CakePdf', array('bootstrap' => true, 'routes' => true));

Configure::write('CakePdf', array(
	'engine' => 'CakePdf.Mpdf',
	'orientation' => 'landscape'
));

However the page is always displayed in portrait. Even if I put the Mpdf custom pagebreak tag in the output
&lt;pagebreak orientation="landscape" /&gt;

**Comment by dakota** [comment]
@Lou2401 Would you be able to open a pull request with that fix?
