### ISSUE TITLE
No CSS or Images

### ISSUE THREAD

**Issue by jammy-git** [FriendsOfCake/CakePdf#41]
I've set up CakePdf in my CakePHP application this evening. I have it generating PDFs in my browser using PdfView, however these PDFs are plain text. It seems like no CSS is being applied, nor do any images show up.

I have CSS files linked in my Layout file, plus I have an image inserted in an element used by that Layout file.

Now, I can only get the PDF to generate if I use relative paths to the files. If I use fullBase the PDF will take ages to load and eventually result in an Internal 500 Error. At which point I have to clear the cookies to my site and re-login.

Any ideas of what I can do to resolve the issue, or steps to debug the problem?

**Comment by arnaubarcelona** [comment]
Sorry, how did you change permissions finally? I'm struggling to do that.
