### ISSUE TITLE
CakePdf ignoring global settings

### ISSUE THREAD

**Issue by pfulop** [FriendsOfCake/CakePdf#49]
Hi there,

I am using the latest CakePDF plugin with wkthmltopdf engine. In my case I have two wkhtmltopdf binaries, version 0.9.9 and 0.11.0 (I needed to use it without X11 and I have not removed the old version).
In my global configuration I have binary path defined to access new version. Everything is working when I am using first method from README "1: Render as pdf (including forced download) in the browser with PdfView". 
If however I want to save it to disk on the server, the pdf does not get rendered with error "WKHTMLTOPDF didn't return any data Error: An Internal Error Has Occurred". I remember this error from time using 0.9.9. So I set the binary path directly in controller 

  $conf = array(    'binary' => '/usr/bin/wkhtmltopdf-amd64'   );
  $CakePdf = new CakePdf($conf);

and it is working. Every other setting from global configuration seems to be applied except binary.

**Comment by dakota** [comment]
Do you still have this problem?

**Comment by designskiller** [comment]
I have still this problem.

**Comment by ADmad** [comment]
@designskiller What problem exactly?
