### ISSUE TITLE
PhantomJS

### ISSUE THREAD

**Issue by develmts** [FriendsOfCake/CakePdf#56]
Anybody considered to add [PhantomJs](http://phantomjs.org) as an engine for PDF rendering ?
Its open Source and multiplatform. It requires to be able to exec a binary ( in the line of 
WkHtmlToPdf, so this shouldn't suppose a problem) and has the added benefit fo rendering also "screenshoots" of webpages,as its a full featured "headless" browser, based on WebKit engine.

**Comment by dakota** [comment]
We would certainly welcome any new engines (As a PR). If you need help, please don't hesitate to ask.
