### ISSUE TITLE
Shell error, return code: 1

### ISSUE THREAD

**Issue by hugofabricio** [FriendsOfCake/CakePdf#60]
Shell error, return code: 1

<?php
	/**
	 * View
	 */
	public function servidor_download($token = null)
	{

		// Se o registro não for encontrado
		if ($result = $this->Movement->find('first', array('recursive' => 2, 'conditions' => array('Movement.token' => $token, 'Movement.servidor_id' => $this->Auth->user('servidor_id'))))):

			$name = sprintf('contracheque-%s-%d', $this->Format->mesExtenso($result['Payroll']['mes']), $result['Payroll']['ano']);

            $this->pdfConfig = array(
		        'engine' => 'CakePdf.WkHtmlToPdf',
                'orientation' => 'portrait',
		        'options' => array(
		            'print-media-type' => true,
		            'outline' => true,
		            'dpi' => 96,
		            'fullBase' => true
		        ),
		        'margin' => array(
		            'bottom' => 15,
		            'left' => 50,
		            'right' => 30,
		            'top' => 45
		        ),
                'download' => false,
                'filename' => $name
            );

			// Set
			$this->set(
				array(
					'result' => $result
				)
			);

		else:

			throw new NotFoundException('Contracheque não encontrado.');

		endif;

	}

**Comment by dakota** [comment]
Not sure what error you are getting?

**Comment by ADmad** [comment]
Closing as this is pretty old and no additional info was provided.
