### ISSUE TITLE
Using helpers in CakePdf

### ISSUE THREAD

**Issue by LDSign** [FriendsOfCake/CakePdf#63]
Hi

I am trying to use helpers in the view when using method 2 mentioned in the docs (save file on disk). Unfortunatley this doesn't work:

$CakePdf = new CakePdf();
$CakePdf->helpers('Html');
...

What I am doing wrong?

Beside of that using this method does ignore the settings made in "Configure" (path to binary) - I have to set it on construct:

$config = array('binary' => Configure::read('CakePdf.binary'));
$CakePdf = new CakePdf($config);

Thanks,
Frank

**Comment by mhagenbruch** [comment]
Is it possible to get an answer for this? Esspecialy on adding css to pdf templates.

**Comment by ADmad** [comment]
With latest version of CakePdf which supports Cake 3.4+ you can use [view builder](https://book.cakephp.org/3.0/en/controllers.html#setting-view-options) to configure helpers as needed.
