### ISSUE TITLE
DomPdf unicode font missing

### ISSUE THREAD

**Issue by mantask** [FriendsOfCake/CakePdf#66]
I'm having an issue with using `CakePdf.DomPdf` engine with unicode chars. The problem is that DomPdf does not include unicode fonts like DejaVu. 

If the CakePdf would include DomPdf as a Packager dependency, the problem would be solved with a newer version of DomPdf. You must have modified DomPdf as a drop-in replacement for `/Plugin/CakePdf/Vendor/dompdf` does not seem to work.

**Comment by josegonzalez** [comment]
We now pull in dompdf via composer, so you can upgrade it at will.
