### ISSUE TITLE
How to add page header/footer to wkhtmltopdf

### ISSUE THREAD

**Issue by nizam27391** [FriendsOfCake/CakePdf#77]
Hi.

I want to add html page header/footer  to my pdf. Right now I hardcode the html table in the view..
But I want to have the header/footer printed automatically at all page.

I read somewhere that for wkhtmltopdf we can use --header-html test.html .......

But how to do it in CakePdf?

Thanx for the help.!

**Comment by amitpanwar86** [comment]
Hi, 

Is there any way to add html content to footer Like "Powered By with an image"??

Thanks In Advance,
Amit

**Comment by zeroasterisk** [comment]
@amitpanwar86 yes - just put it in the HTML as an `<img` with a full URL as the `src`

**Comment by filippogiordano** [comment]
This code doesn't add any header/footer on my pdf..
Do you know why?
I'm using cakephp 3.1 and my cakepdf component is working.
This is my code:
$this->viewBuilder()->options([
    			'pdfConfig' => [
    					'filename' => 'audizione_' . $id.'.pdf',
    					//'print-media-type' => false,
                		//'outline' => true,
                		'dpi' => 500,
    					'margin' => [
    							'bottom' => 5,
    							'left' => 4,
    							'right' => 4,
    							'top' => 5
    					],
    					'orientation' => 'portrait',
    					'download' => true,
    					'header-html' =>'Ciao'
    					//'engine' => 'CakePdf.WkHtmlToPdf',
    					'options' => [
            				'print-media-type' => false,
            				'outline'          => true,
            				'dpi'              => 96,
            				'footer-center'     => 'foobar HERE &copy; ' . date('Y'),
            				'footer-right'     => 'Page [page] of [toPage]',
        ],
    			]
    	]);

**Comment by rthakur** [comment]
@filippogiordano  please check wkhtmltopdf --version

**Comment by filippogiordano** [comment]
I solved the problem with this configuration.
Configure::write('CakePdf', [
		'engine' => [
            'className' => 'CakePdf.WkHtmlToPdf',
            'binary' => '/usr/local/bin/wkhtmltopdf',
            'options' => [
                'print-media-type' => false,
                'outline' => true,
                'dpi' => 500,
            	'header-html'=>"http://.....headeraddress",
            	'footer-html'=>"http://...footeraddress",
            	'footer-right'=>"Pag. [page] di [toPage]",
            	'header-spacing'=>1,
            	'footer-spacing' => '1',
            ],
        ],
		'margin' => [
				'bottom' => 20,
				'left'   => 20,
				'right'  => 20,
				'top'    => 45
		],
		'download' => false
]);

and adding to the first line of my header and footer html:
<!DOCTYPE html>

**Comment by Jovelasquez** [comment]
Please, who can help me?

How to add header and footer with wkhtmltopdf dynamically to my pdf?
