### ISSUE TITLE
composer name wrong

### ISSUE THREAD

**Issue by dereuromark** [FriendsOfCake/CakePdf#79]
Seems like the composer name is in same cases not `"name": "friendsofcake/cakepdf"` which it should be, but "cake-pdf" etc, README for example:

    composer require friendsofcake/cake-pdf

This should be revised.

**Comment by hughc** [comment]
readme.md still says 

`
 composer require friendsofcake/cake-pdf
`

**Comment by wp4nuv** [comment]
FYI, the README is still incorrect, using friendsofcake/cake-pdf instead of friendsofcake/cakepdf.

**Comment by dereuromark** [comment]
Fixed with https://github.com/FriendsOfCake/CakePdf/commit/d5f12a2e33228327de0ce3c9c803adfc5d4a0699
