### ISSUE TITLE
How to add page header/footer using TCPDF engine

### ISSUE THREAD

**Issue by alicja123456** [FriendsOfCake/CakePdf#82]
Hi ;)
I would like to add footer to my pdf. Code below doesn't seem to work for me:
$CakePdf->footer("Left part", "Center", "Page x of X");
Used before:
$CakePdf->template('docs/view', 'default');
Can anyone help me with this, please?

**Comment by cnpisit** [comment]
@zeroasterisk, I am not sure that WkHtmlToPdf engine (much better). but I just want to know how to custom footer by using Tcpdf engine.
