### ISSUE TITLE
Default layout path when RequestHandler is enabled

### ISSUE THREAD

**Issue by davidsteinsland** [FriendsOfCake/CakePdf#89]
If I have RequestHandler enabled, the PDF output works just fine when adding `.pdf` suffix.
However, if I don't add it, I want to be able to render the view and serve it as HTML. Useful for a "Preview" option.

In order to achieve this, I have to set:
```php
if (!in_array($this->viewClass, array('Pdf', 'CakePdf.Pdf'))) {
    $this->layoutPath = 'pdf';
    $this->viewPath = 'ControllerName/pdf';
}
```

Without the if statement, CakePdf tries to load: `View/ControllerName/pdf/pdf/pdf.ctp`. Same issue if I just use:

```php
public function view() {
    // .....
    return $this->render('pdf/view', 'pdf/default');
}
```

---

Proposal: Without any user code, render correct layout and view whether PDF is generated or not.
That is: `Layouts/Pdf/default.ctp` and `ControllerName/pdf/view.ctp`.

The only difference is that when ".pdf" is added, a PDF is created.

OR: Fix so that setting `layoutPath` or `viewPath` works, without the if statement.

**Comment by ceeram** [comment]
if you don't add the .pdf url extension, it is a normal request with html
response in cakephp.

It would just use the regular .ctp files and works fine for me. Please
provide the code to reproduce this problem


2015-01-21 20:48 GMT+01:00 David Steinsland <notifications@github.com>:

**Comment by davidsteinsland** [comment]
Just try this, with and without ".pdf":
```php
public function view() {
    // .....
    return $this->render('pdf/view', 'pdf/default');
}
```

The idea is to render the PDF views both when producing a PDF and when returning HTML.

**Comment by ceeram** [comment]
Just tried that and it works fine. I can go to articles/view/1 to get normal html view, i can go to articles/view/1.pdf to see the pdf, then i changed the code with the render() statement you gave.
articles/view/1 now gives me html response with using Articles/pdf/view.ctp and Layouts/pdf/default.ctp

**Comment by davidsteinsland** [comment]
Did you test on `dev-master` or `1.0.2`?

**Comment by ceeram** [comment]
I used master, but would not make a difference, the only difference between 1.0.2 and master are some readme, license and composer changes: https://github.com/FriendsOfCake/CakePdf/compare/1.0.2...master
