### ISSUE TITLE
CakePDF with CakePHP v3 RC1

### ISSUE THREAD

**Issue by cyberbobjr** [FriendsOfCake/CakePdf#91]
Hi Everybody,
I use CakePDF branch for CakePHP v3, i follow step by step the readme text, and installation of CakePDF is easy with composer. But i can't generate & display PDF request, every time i have my "simple html" view displayed instead of pdf view.
I created a "pdf" dir under Templates/Commandes/ with a view.ctp inside it.
I put the Plugin::load('CakePdf', array('bootstrap' => TRUE, 'routes' => TRUE)); in bootstrap.
I have a pdf layout inside Templates/layout with only this line "<?= $this->fetch('content') ?>"

But if i go to /commandes/view/1.pdf, i don't see the pdf file, only the view.ctp inside /Templates/Commandes/

Someone have this issue too ?
Thanks
Regards

**Comment by dereuromark** [comment]
I think the readme / docs should also mention the usage of extensions() and RequestHandler to be able to use ext URLs like `/controller/action.pdf` - which then can automatically switch to the PdfView.

**Comment by cyberbobjr** [comment]
Yeah you're right ! finally i've find the trick with your help :
put this :
```` Router::extensions(['html', 'rss', 'pdf']);````
in the file routes.php
Many thanks
Regards

**Comment by dereuromark** [comment]
@jadb the docs dont mention it just yet
@cyberbobjr you mind maybe adding a note about it to the docs?

**Comment by ceeram** [comment]
If loaded correctly, this shouldnt be necesarry? https://github.com/FriendsOfCake/CakePdf/blob/3.0/config/routes.php#L4

**Comment by jadb** [comment]
@dereuromark  sorry for closing too early. I read many thanks and assumed it was done. FAIL.

**Comment by dereuromark** [comment]
Isnt the request handler necessary to auto-switch the view class?

**Comment by ceeram** [comment]
The requesthandler is, adding pdf to extensions isnt.
The readme already states to include RH component:
https://github.com/FriendsOfCake/CakePdf/blob/3.0/README.md#1-render-as-pdf-including-forced-download-in-the-browser-with-pdfview

@dereuromark what is your point exactly?

2015-02-06 20:49 GMT+01:00 Mark S. <notifications@github.com>:

**Comment by dereuromark** [comment]
Well then it's all fine.
