### ISSUE TITLE
Overwriting of existing timezone configuration

### ISSUE THREAD

**Issue by simonberger** [FriendsOfCake/CakePdf#92]
In mpdf.php line 54-56 we have the code block

`if(function_exists("date_default_timezone_set")) {
	if (ini_get("date.timezone")=="") { date_default_timezone_set("Europe/London"); }
}`

It is highly possible (we have the problem) that it overwrites the timezone of code following the pdf creation. At least in later php versions.

Something like

`date_default_timezone_set(date_default_timezone_get())`

could do the trick if timezone UTC as a fallback is ok.

**Comment by ceeram** [comment]
This should be fixed in the upstream mpdf.php file. Currently all vendor code is still included, this has been removed in the Cake 3 version.

**Comment by simonberger** [comment]
An update to cakephp is not planned in the nearer future.
Do you mean you push an updated mpdf.php file soon? This bug is in the latest mpdf release itself too.

**Comment by ADmad** [comment]
You avoid the problem by setting the `"date.timezone"` ini value. Or use another engine.
