### ISSUE TITLE
pdfOptions in view of controller does not work in 3.0 branch

### ISSUE THREAD

**Issue by Bzounourz** [FriendsOfCake/CakePdf#93]
Everything works fine when I load the options via the bootstrap file:

Configure::write('CakePdf', [
    'engine' => [
        'className' => 'CakePdf.WkHtmlToPdf',
        'options' => [
            'header-html' => 'url/header.html',
            'footer-right'     => 'Page [page] sur [toPage]',
        ]
    ],
    'margin' => [
        'bottom' => 10,
        'left' => 10,
        'right' => 10,
        'top' => 45
    ]
]);

But when I want to change some options, nothing is taken into account, I pass by the controller or by the view.

If I call the helpers I have this error:

Error: Call to undefined method CakePdf\View\PdfView::pdfOptions() 

Thank you in advance for your help.

**Comment by p-try** [comment]
I can confirm this, $this->pdfOptions is ignored in the 3.0 branch.

**Comment by p-try** [comment]
I can confirm that $this->pdfConfig is ignored. I have found a solution for it. In 3.0, passed vars from the controller are restricted in Controller::_validViewOptions. You have to add 'pdfConfig' to this array in your controller:
```php
public function initialize()
{
	parent::initialize();
        $this->_validViewOptions[] = 'pdfConfig';
}
```
Then you can use $this->pdfConfig to set options:
```php
$this->pdfConfig = [
    'orientation' => 'landscape'
];
```
I think this shold be integrated in the plugin somewhere so we don't have to set this for every controller.

**Comment by ADmad** [comment]
This has been fixed.
