### ISSUE TITLE
System Error

### ISSUE THREAD

**Issue by boyedokup** [FriendsOfCake/CakePdf#94]
How do I solve this
System error <pre>Exit with code 1 due to network error: ContentNotFoundError </pre>

**Comment by ceeram** [comment]
Neve seen that one before, how can i reproduce it?

2015-03-13 11:58 GMT+01:00 boyedokup <notifications@github.com>:

**Comment by boyedokup** [comment]
So i put my layout into view/layout/pdf/pdf.ctp and controller view into
view/applicants/pdf/applicants_pdf.ctp
When i run localhost/admin/applicants/applicants_pdf/12322.pdf

Then i get the error

On Fri, Mar 13, 2015 at 11:04 AM, ceeram <notifications@github.com> wrote:

> Neve seen that one before, how can i reproduce it?
>
> 2015-03-13 11:58 GMT+01:00 boyedokup <notifications@github.com>:
>
> > How do I solve this
> > System error
> >
> > Exit with code 1 due to network error: ContentNotFoundError
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/FriendsOfCake/CakePdf/issues/94>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FriendsOfCake/CakePdf/issues/94#issuecomment-78920053>
> .
>



-- 
*Philip Boye-Doku*
*First Capital Plus Bank*
*Applications Developer*

**Comment by boyedokup** [comment]
System error <pre>Exit with code 1 due to network error:
ContentNotFoundError </pre>

On Fri, Mar 13, 2015 at 11:16 AM, philip boye-doku <boyedokup@gmail.com>
wrote:

> So i put my layout into view/layout/pdf/pdf.ctp and controller view into
> view/applicants/pdf/applicants_pdf.ctp
> When i run localhost/admin/applicants/applicants_pdf/12322.pdf
>
> Then i get the error
>
> On Fri, Mar 13, 2015 at 11:04 AM, ceeram <notifications@github.com> wrote:
>
>> Neve seen that one before, how can i reproduce it?
>>
>> 2015-03-13 11:58 GMT+01:00 boyedokup <notifications@github.com>:
>>
>> > How do I solve this
>> > System error
>> >
>> > Exit with code 1 due to network error: ContentNotFoundError
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/FriendsOfCake/CakePdf/issues/94>.
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/FriendsOfCake/CakePdf/issues/94#issuecomment-78920053>
>> .
>>
>
>
>
> --
> *Philip Boye-Doku*
> *First Capital Plus Bank*
> *Applications Developer*
>



-- 
*Philip Boye-Doku*
*First Capital Plus Bank*
*Applications Developer*

**Comment by ceeram** [comment]
Do you have external css in your layout? can you perhaps show your layout?

2015-03-13 12:17 GMT+01:00 boyedokup <notifications@github.com>:

**Comment by ceeram** [comment]
Also a stack trace would be nice to have

2015-03-13 12:43 GMT+01:00 Ceeram <c33ram@gmail.com>:

**Comment by boyedokup** [comment]
<?php
/**
 *
 * PHP 5
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc.
(http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @package       app.View.Layouts
 * @since         CakePHP(tm) v 0.10.0.1076
 * @license       MIT License
(http://www.opensource.org/licenses/mit-license.php)
 */

$ashAdmissionDescription = __d('cake_dev', 'Admin Console : AshAdmission');
?>
<!DOCTYPE html>
<html>
<head>
   <?php echo $this->Html->charset(); ?>
   <title>
      <?php echo $ashAdmissionDescription ?>:
      <?php echo $title_for_layout; ?>
   </title>
   <?php
      echo $this->Html->meta('icon');

      echo $this->Html->css('bootstrap');
      echo $this->Html->css('animate');
      echo $this->Html->css('font-awesome');
      echo $this->Html->css('custom');
      echo $this->Html->css('dataTables.bootstrap');
      echo $this->Html->css('http://fonts.googleapis.com/css?family=Open+Sans');

      echo $this->fetch('meta');
      echo $this->fetch('css');
      echo $this->fetch('script');
   ?>

</head>
<body>


        
        
      <div id="page-wrapper" style='margin:0px'>
         <div class="faq2 above color-white text-center padding-10"
onclick="dropdown();">
                <a class="color-white" data-toggle="dropdown">
                    <i class="fa fa-cog fa-2x"></i>
                    <span class="caret"></span>
                </a>
                 <ul class="dropdown-menu" >
                    
                    <li><?php echo $this->Html->link('Logout',
array('controller' => 'users', 'action' => 'logout')); ?></li>
                    <li class="dl-horizontal"></li>
                    
                </ul>
            </div>
            <div class="panel panel-default">
            <div class="panel-body">

         <?php echo $this->Session->flash(); ?>

         <?php echo $this->fetch('content'); ?>
         <?php echo $this->element('applicant_pdf'); ?>
         <?php echo $this->element('admission_pdf'); ?>
            <?php echo $this->element('relatives_pdf'); ?>
            <?php echo $this->element('schools_pdf'); ?>
            <?php echo $this->element('travel_pdf'); ?>
            <?php echo $this->element('works_pdf'); ?>
            <?php echo $this->element('otherColleges_pdf'); ?>
            <?php
if($this->Session->read('check_for_financial_aid')=='Yes'){ ?>
            <?php echo $this->element('fa_application_pdf'); ?>
            <?php echo $this->element('fa_dependants_pdf'); ?>
            <?php echo $this->element('fa_incomes_pdf'); ?>
            <?php echo $this->element('fa_expense_pdf'); ?>
            <?php echo $this->element('fa_assets_pdf'); ?>
            <?php echo $this->element('fa_debts_pdf'); ?>
            <?php echo $this->element('fa_financiers_pdf'); ?>
            <?php echo $this->element('fa_scholarship_pdf'); ?>
             <?php echo $this->element('fa_references_pdf');} ?>
            </div>
            </div>
      </div>
      <div id="footer">
         <?php //echo $this->Html->link(
               //$this->Html->image('cake.power.gif', array('alt' =>
$ashAdmissionDescription, 'border' => '0')),
               //'http://www.cakephp.org/',
               //array('target' => '_blank', 'escape' => false)
            //);
         ?>
      </div>
   </div>
   <?php
     // echo $this->element('sql_dump');
      echo $this->Html->script('jquery-2.1.1.min');
      echo $this->Html->script('jquery.metisMenu');
      echo $this->Html->script('bootstrap.min');
      echo $this->Html->script('dataTables/dataTables.bootstrap');
      echo $this->Html->script('custom');
    ?>
    <style>
         body
         {
         margin:0px;
         padding:0px;



         }
         div
         {
           margin:0px;
           padding:0px;
         }

        </style>
</body>
</html>


On Fri, Mar 13, 2015 at 11:44 AM, ceeram <notifications@github.com> wrote:

> Also a stack trace would be nice to have
>
>
> 2015-03-13 12:43 GMT+01:00 Ceeram <c33ram@gmail.com>:
>
> > Do you have external css in your layout? can you perhaps show your
> layout?
> >
> > 2015-03-13 12:17 GMT+01:00 boyedokup <notifications@github.com>:
> >
> >> System error <pre>Exit with code 1 due to network error:
> >> ContentNotFoundError </pre>
> >>
> >> On Fri, Mar 13, 2015 at 11:16 AM, philip boye-doku <boyedokup@gmail.com
> >
> >> wrote:
> >>
> >> > So i put my layout into view/layout/pdf/pdf.ctp and controller view
> into
> >> > view/applicants/pdf/applicants_pdf.ctp
> >> > When i run localhost/admin/applicants/applicants_pdf/12322.pdf
> >> >
> >> > Then i get the error
> >> >
> >> > On Fri, Mar 13, 2015 at 11:04 AM, ceeram <notifications@github.com>
> >> wrote:
> >> >
> >> >> Neve seen that one before, how can i reproduce it?
> >> >>
> >> >> 2015-03-13 11:58 GMT+01:00 boyedokup <notifications@github.com>:
> >> >>
> >> >> > How do I solve this
> >> >> > System error
> >> >> >
> >> >> > Exit with code 1 due to network error: ContentNotFoundError
> >> >> >
> >> >> > —
> >> >> > Reply to this email directly or view it on GitHub
> >> >> > <https://github.com/FriendsOfCake/CakePdf/issues/94>.
> >> >> >
> >> >>
> >> >> —
> >> >> Reply to this email directly or view it on GitHub
> >> >> <
> >>
> https://github.com/FriendsOfCake/CakePdf/issues/94#issuecomment-78920053>
> >> >> .
> >> >>
> >> >
> >> >
> >> >
> >> > --
> >> > *Philip Boye-Doku*
> >> > *First Capital Plus Bank*
> >> > *Applications Developer*
> >> >
> >>
> >>
> >>
> >> --
> >> *Philip Boye-Doku*
> >> *First Capital Plus Bank*
> >> *Applications Developer*
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <
> https://github.com/FriendsOfCake/CakePdf/issues/94#issuecomment-78924328>
> >> .
> >>
> >
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FriendsOfCake/CakePdf/issues/94#issuecomment-78933305>
> .
>



-- 
*Philip Boye-Doku*
*First Capital Plus Bank*
*Applications Developer*

**Comment by boyedokup** [comment]
- APP\Plugin\CakePdf\Pdf\CakePdf.php line 236
   <http://localhost/admin/applicants/text_pdf.pdf#> →
   WkHtmlToPdfEngine->output()
   <http://localhost/admin/applicants/text_pdf.pdf#>
   - APP\Plugin\CakePdf\View\PdfView.php line 97
   <http://localhost/admin/applicants/text_pdf.pdf#> →
   CakePdf->output(string) <http://localhost/admin/applicants/text_pdf.pdf#>
   - CORE\Cake\Controller\Controller.php line 948
   <http://localhost/admin/applicants/text_pdf.pdf#> →PdfView->render(null,
   null) <http://localhost/admin/applicants/text_pdf.pdf#>
   - CORE\Cake\Routing\Dispatcher.php line 194
   <http://localhost/admin/applicants/text_pdf.pdf#> →Controller->render()
   <http://localhost/admin/applicants/text_pdf.pdf#>
   - CORE\Cake\Routing\Dispatcher.php line 162
   <http://localhost/admin/applicants/text_pdf.pdf#>
→Dispatcher->_invoke(ApplicantsController,
   CakeRequest, CakeResponse)
   <http://localhost/admin/applicants/text_pdf.pdf#>
   - APP\webroot\index.php line 109
   <http://localhost/admin/applicants/text_pdf.pdf#> →
Dispatcher->dispatch(CakeRequest,
   CakeResponse) <http://localhost/admin/applicants/text_pdf.pdf#>


On Fri, Mar 13, 2015 at 11:51 AM, philip boye-doku <boyedokup@gmail.com>
wrote:

> <?php
> /**
>  *
>  * PHP 5
>  *
>  * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
>  * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
>  *
>  * Licensed under The MIT License
>  * For full copyright and license information, please see the LICENSE.txt
>  * Redistributions of files must retain the above copyright notice.
>  *
>  * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
>  * @link          http://cakephp.org CakePHP(tm) Project
>  * @package       app.View.Layouts
>  * @since         CakePHP(tm) v 0.10.0.1076
>  * @license       MIT License (http://www.opensource.org/licenses/mit-license.php)
>  */
>
> $ashAdmissionDescription = __d('cake_dev', 'Admin Console : AshAdmission');
> ?>
> <!DOCTYPE html>
> <html>
> <head>
>    <?php echo $this->Html->charset(); ?>
>    <title>
>       <?php echo $ashAdmissionDescription ?>:
>       <?php echo $title_for_layout; ?>
>    </title>
>    <?php
>       echo $this->Html->meta('icon');
>
>       echo $this->Html->css('bootstrap');
>       echo $this->Html->css('animate');
>       echo $this->Html->css('font-awesome');
>       echo $this->Html->css('custom');
>       echo $this->Html->css('dataTables.bootstrap');
>       echo $this->Html->css('http://fonts.googleapis.com/css?family=Open+Sans');
>
>       echo $this->fetch('meta');
>       echo $this->fetch('css');
>       echo $this->fetch('script');
>    ?>
>
> </head>
> <body>
>
>
>         
>         
>       <div id="page-wrapper" style='margin:0px'>
>          <div class="faq2 above color-white text-center padding-10" onclick="dropdown();">
>                 <a class="color-white" data-toggle="dropdown">
>                     <i class="fa fa-cog fa-2x"></i>
>                     <span class="caret"></span>
>                 </a>
>                  <ul class="dropdown-menu" >
>                     
>                     <li><?php echo $this->Html->link('Logout',  array('controller' => 'users', 'action' => 'logout')); ?></li>
>                     <li class="dl-horizontal"></li>
>                     
>                 </ul>
>             </div>
>             <div class="panel panel-default">
>             <div class="panel-body">
>
>          <?php echo $this->Session->flash(); ?>
>
>          <?php echo $this->fetch('content'); ?>
>          <?php echo $this->element('applicant_pdf'); ?>
>          <?php echo $this->element('admission_pdf'); ?>
>             <?php echo $this->element('relatives_pdf'); ?>
>             <?php echo $this->element('schools_pdf'); ?>
>             <?php echo $this->element('travel_pdf'); ?>
>             <?php echo $this->element('works_pdf'); ?>
>             <?php echo $this->element('otherColleges_pdf'); ?>
>             <?php  if($this->Session->read('check_for_financial_aid')=='Yes'){ ?>
>             <?php echo $this->element('fa_application_pdf'); ?>
>             <?php echo $this->element('fa_dependants_pdf'); ?>
>             <?php echo $this->element('fa_incomes_pdf'); ?>
>             <?php echo $this->element('fa_expense_pdf'); ?>
>             <?php echo $this->element('fa_assets_pdf'); ?>
>             <?php echo $this->element('fa_debts_pdf'); ?>
>             <?php echo $this->element('fa_financiers_pdf'); ?>
>             <?php echo $this->element('fa_scholarship_pdf'); ?>
>              <?php echo $this->element('fa_references_pdf');} ?>
>             </div>
>             </div>
>       </div>
>       <div id="footer">
>          <?php //echo $this->Html->link(
>                //$this->Html->image('cake.power.gif', array('alt' => $ashAdmissionDescription, 'border' => '0')),
>                //'http://www.cakephp.org/',
>                //array('target' => '_blank', 'escape' => false)
>             //);
>          ?>
>       </div>
>    </div>
>    <?php
>      // echo $this->element('sql_dump');
>       echo $this->Html->script('jquery-2.1.1.min');
>       echo $this->Html->script('jquery.metisMenu');
>       echo $this->Html->script('bootstrap.min');
>       echo $this->Html->script('dataTables/dataTables.bootstrap');
>       echo $this->Html->script('custom');
>     ?>
>     <style>
>          body
>          {
>          margin:0px;
>          padding:0px;
>
>
>
>          }
>          div
>          {
>            margin:0px;
>            padding:0px;
>          }
>
>         </style>
> </body>
> </html>
>
>
> On Fri, Mar 13, 2015 at 11:44 AM, ceeram <notifications@github.com> wrote:
>
>> Also a stack trace would be nice to have
>>
>>
>> 2015-03-13 12:43 GMT+01:00 Ceeram <c33ram@gmail.com>:
>>
>> > Do you have external css in your layout? can you perhaps show your
>> layout?
>> >
>> > 2015-03-13 12:17 GMT+01:00 boyedokup <notifications@github.com>:
>> >
>> >> System error <pre>Exit with code 1 due to network error:
>> >> ContentNotFoundError </pre>
>> >>
>> >> On Fri, Mar 13, 2015 at 11:16 AM, philip boye-doku <
>> boyedokup@gmail.com>
>> >> wrote:
>> >>
>> >> > So i put my layout into view/layout/pdf/pdf.ctp and controller view
>> into
>> >> > view/applicants/pdf/applicants_pdf.ctp
>> >> > When i run localhost/admin/applicants/applicants_pdf/12322.pdf
>> >> >
>> >> > Then i get the error
>> >> >
>> >> > On Fri, Mar 13, 2015 at 11:04 AM, ceeram <notifications@github.com>
>> >> wrote:
>> >> >
>> >> >> Neve seen that one before, how can i reproduce it?
>> >> >>
>> >> >> 2015-03-13 11:58 GMT+01:00 boyedokup <notifications@github.com>:
>> >> >>
>> >> >> > How do I solve this
>> >> >> > System error
>> >> >> >
>> >> >> > Exit with code 1 due to network error: ContentNotFoundError
>> >> >> >
>> >> >> > —
>> >> >> > Reply to this email directly or view it on GitHub
>> >> >> > <https://github.com/FriendsOfCake/CakePdf/issues/94>.
>> >> >> >
>> >> >>
>> >> >> —
>> >> >> Reply to this email directly or view it on GitHub
>> >> >> <
>> >>
>> https://github.com/FriendsOfCake/CakePdf/issues/94#issuecomment-78920053>
>> >> >> .
>> >> >>
>> >> >
>> >> >
>> >> >
>> >> > --
>> >> > *Philip Boye-Doku*
>> >> > *First Capital Plus Bank*
>> >> > *Applications Developer*
>> >> >
>> >>
>> >>
>> >>
>> >> --
>> >> *Philip Boye-Doku*
>> >> *First Capital Plus Bank*
>> >> *Applications Developer*
>> >>
>> >> —
>> >> Reply to this email directly or view it on GitHub
>> >> <
>> https://github.com/FriendsOfCake/CakePdf/issues/94#issuecomment-78924328>
>> >> .
>> >>
>> >
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/FriendsOfCake/CakePdf/issues/94#issuecomment-78933305>
>> .
>>
>
>
>
> --
> *Philip Boye-Doku*
> *First Capital Plus Bank*
> *Applications Developer*
>



-- 
*Philip Boye-Doku*
*First Capital Plus Bank*
*Applications Developer*

**Comment by ceeram** [comment]
You have many external assets, both css as js scripts. You need to make sure all the needed css and js are included in the layout itself instead of through external files

**Comment by ceeram** [comment]
Ow, or offourse this one: https://github.com/FriendsOfCake/CakePdf#note-about-static-assets

**Comment by boyedokup** [comment]
Thanks very much
1) I removed the external css
2) Added the code snippet to my AppHelper Class

 https://github.com/FriendsOfCake/CakePdf#note-about-static-assets

On Fri, Mar 13, 2015 at 12:08 PM, ceeram <notifications@github.com> wrote:

> Ow, or offourse this one:
> https://github.com/FriendsOfCake/CakePdf#note-about-static-assets
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FriendsOfCake/CakePdf/issues/94#issuecomment-78941865>
> .
>



-- 
*Philip Boye-Doku*
*First Capital Plus Bank*
*Applications Developer*

**Comment by ceeram** [comment]
ok
