### ISSUE TITLE
wkhtmltopdf didn't return any data

### ISSUE THREAD

**Issue by nizam27391** [FriendsOfCake/CakePdf#98]
Hi.

I have this problem with CakePdf. It throws an error saying ```wkhtmltopdf didn't return any data```
I have two server - one is development, one is staging server..

It works fine in development server, but when we upload the files to staging server and configure it to be the same as development server, it throws that error.

I've been trying to solve this issue including installing new wkhtmltopdf for days and none is working.

Please help me. :(

**Comment by AgentStephens** [comment]
Check that you have set the path to the binary. 

Something like 

```
'binary' => '/usr/local/bin/wkhtmltopdf'
```

**Comment by nizam27391** [comment]
yeap.. that one is done also.. 

I've fixed this issue.. its due to selinux being enabled.. after disabled it seems to be working fine..

Thanks
