### ISSUE TITLE
pageSize for DomPdf engine not working!

### ISSUE THREAD

**Issue by kfelahiju** [FriendsOfCake/CakePdf#99]
I have to work with domPdf engine but the pageSize is always remains in A4. Is it possible to change the default page size to Letter anyway?

Configure::write('CakePdf', array(
        'engine' => 'CakePdf.DomPdf',
        'options' => array(
            'print-media-type' => false,
            'outline' => true,
            'dpi' => 96
        ),
        'margin' => array(
            'bottom' => 15,
            'left' => 50,
            'right' => 30,
            'top' => 45
        ),
        'pageSize'=>'Letter',
        'orientation' => 'portrait',
    ));

**Comment by kfelahiju** [comment]
I got the solution. I have to define the pageSize in the controller after creating instance.

**Comment by metaled** [comment]
Please tell me if you tried the plugin in CakePHP 3.x with DomPdf engine because it has my not work for me.
Thank You

**Comment by moretty** [comment]
again... undefined "explode_url()" an decens of warnings because it's not loading the config and functions... any tip?

**Comment by ADmad** [comment]
Issue with dompdf engine has been fixed.
